package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

// EnsureClientEntryMonitorSchema creates persistence for TCP monitoring of
// client-entry policies. The monitor is deliberately separate from DNS
// failover state: an unhealthy client entry can notify operators, but cannot
// accidentally trigger a DNS mutation.
func EnsureClientEntryMonitorSchema(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db is nil")
	}

	for _, stmt := range clientEntryMonitorTableStatements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry monitor table: %w", err)
		}
	}
	for _, stmt := range clientEntryMonitorMigrationStatements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("migrate client entry monitor schema: %w", err)
		}
	}

	for _, constraint := range clientEntryMonitorConstraints {
		stmt := fmt.Sprintf(`DO $client_entry_monitor$
BEGIN
ALTER TABLE %s ADD CONSTRAINT %s %s;
EXCEPTION
WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_monitor$;`, constraint.table, constraint.name, constraint.definition)
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry monitor constraint %s: %w", constraint.name, err)
		}
	}

	for _, stmt := range clientEntryMonitorIndexStatements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry monitor index: %w", err)
		}
	}
	if _, err := db.ExecContext(ctx, clientEntryMonitorConfigSeedStatement); err != nil {
		return fmt.Errorf("ensure client entry monitor config singleton: %w", err)
	}
	return nil
}

var clientEntryMonitorTableStatements = []string{
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_config (
id SMALLINT NOT NULL,
revision BIGINT NOT NULL DEFAULT 1,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
policy_id INTEGER NOT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
check_interval_sec INTEGER NOT NULL DEFAULT 30,
tcp_timeout_ms INTEGER NOT NULL DEFAULT 3000,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_target (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
monitor_id BIGINT NOT NULL,
source_key varchar(255) NOT NULL,
name varchar(255) NOT NULL DEFAULT '',
host varchar(255) NOT NULL,
port INTEGER NOT NULL,
generation BIGINT NOT NULL DEFAULT 1,
sort INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_probe (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
monitor_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_state (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
target_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
last_success SMALLINT DEFAULT NULL,
last_latency_ms INTEGER DEFAULT NULL,
last_error text NOT NULL DEFAULT '',
last_resolved_ip varchar(128) NOT NULL DEFAULT '',
consecutive_success INTEGER NOT NULL DEFAULT 0,
consecutive_failure INTEGER NOT NULL DEFAULT 0,
last_reported_at BIGINT DEFAULT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_event (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
monitor_id BIGINT NOT NULL,
target_id BIGINT DEFAULT NULL,
probe_id BIGINT DEFAULT NULL,
event_type varchar(32) NOT NULL,
message text NOT NULL DEFAULT '',
details text NOT NULL DEFAULT '{}',
notified_at BIGINT DEFAULT NULL,
notify_attempts INTEGER NOT NULL DEFAULT 0,
notify_next_attempt_at BIGINT NOT NULL DEFAULT 0,
last_notify_error text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_event_delivery (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
event_id BIGINT NOT NULL,
chat_id BIGINT NOT NULL,
delivered_at BIGINT DEFAULT NULL,
attempts INTEGER NOT NULL DEFAULT 0,
next_attempt_at BIGINT NOT NULL DEFAULT 0,
last_error text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_run (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
requested_by_user_id INTEGER DEFAULT NULL,
request_chat_id BIGINT DEFAULT NULL,
request_key varchar(255) DEFAULT NULL,
policy_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
expected_pairs jsonb NOT NULL DEFAULT '[]'::jsonb,
status varchar(32) NOT NULL DEFAULT 'pending',
expected_results INTEGER NOT NULL DEFAULT 0,
received_results INTEGER NOT NULL DEFAULT 0,
started_at BIGINT DEFAULT NULL,
completed_at BIGINT DEFAULT NULL,
notified_at BIGINT DEFAULT NULL,
notify_attempts INTEGER NOT NULL DEFAULT 0,
notify_next_attempt_at BIGINT NOT NULL DEFAULT 0,
last_notify_error text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_run_result (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
run_id BIGINT NOT NULL,
target_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
target_name varchar(255) NOT NULL DEFAULT '',
host varchar(255) NOT NULL DEFAULT '',
port INTEGER NOT NULL DEFAULT 443,
probe_name varchar(255) NOT NULL DEFAULT '',
success SMALLINT NOT NULL,
latency_ms INTEGER DEFAULT NULL,
error text NOT NULL DEFAULT '',
resolved_ip varchar(128) NOT NULL DEFAULT '',
reported_at BIGINT NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_result_inbox (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
probe_id BIGINT NOT NULL,
target_id BIGINT DEFAULT NULL,
run_id BIGINT DEFAULT NULL,
result_id varchar(128) NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
}

var clientEntryMonitorMigrationStatements = []string{
	`ALTER TABLE v2_client_entry_monitor_event ADD COLUMN IF NOT EXISTS notify_next_attempt_at BIGINT NOT NULL DEFAULT 0`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS request_key varchar(255) DEFAULT NULL`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS expected_pairs jsonb NOT NULL DEFAULT '[]'::jsonb`,
	`ALTER TABLE v2_client_entry_monitor_target ADD COLUMN IF NOT EXISTS generation BIGINT NOT NULL DEFAULT 1`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS target_name varchar(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS host varchar(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS port INTEGER NOT NULL DEFAULT 443`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS probe_name varchar(255) NOT NULL DEFAULT ''`,
}

const clientEntryMonitorConfigSeedStatement = `INSERT INTO v2_client_entry_monitor_config (id, revision, updated_at)
VALUES (1, 1, 0)
ON CONFLICT (id) DO NOTHING`

var clientEntryMonitorConstraints = []struct {
	table      string
	name       string
	definition string
}{
	{"v2_client_entry_monitor_config", "chk_v2_client_entry_monitor_config_singleton", "CHECK (id = 1)"},
	{"v2_client_entry_monitor_config", "chk_v2_client_entry_monitor_config_revision", "CHECK (revision > 0)"},
	{"v2_client_entry_monitor", "fk_v2_client_entry_monitor_policy", "FOREIGN KEY (policy_id) REFERENCES v2_client_entry_user_policy(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor", "uniq_v2_client_entry_monitor_policy", "UNIQUE (policy_id)"},
	{"v2_client_entry_monitor", "chk_v2_client_entry_monitor_enabled", "CHECK (enabled IN (0, 1))"},
	{"v2_client_entry_monitor", "chk_v2_client_entry_monitor_timing", "CHECK (check_interval_sec > 0 AND tcp_timeout_ms > 0)"},
	{"v2_client_entry_monitor_target", "fk_v2_client_entry_monitor_target_monitor", "FOREIGN KEY (monitor_id) REFERENCES v2_client_entry_monitor(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_target", "uniq_v2_client_entry_monitor_target_source", "UNIQUE (monitor_id, source_key)"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_source", "CHECK (btrim(source_key) <> '')"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_host", "CHECK (btrim(host) <> '')"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_port", "CHECK (port BETWEEN 1 AND 65535)"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_generation", "CHECK (generation > 0)"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_sort", "CHECK (sort >= 0)"},
	{"v2_client_entry_monitor_probe", "fk_v2_client_entry_monitor_probe_monitor", "FOREIGN KEY (monitor_id) REFERENCES v2_client_entry_monitor(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_probe", "fk_v2_client_entry_monitor_probe_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_probe", "uniq_v2_client_entry_monitor_probe", "UNIQUE (monitor_id, probe_id)"},
	{"v2_client_entry_monitor_state", "fk_v2_client_entry_monitor_state_target", "FOREIGN KEY (target_id) REFERENCES v2_client_entry_monitor_target(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_state", "fk_v2_client_entry_monitor_state_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_state", "uniq_v2_client_entry_monitor_state", "UNIQUE (target_id, probe_id)"},
	{"v2_client_entry_monitor_state", "chk_v2_client_entry_monitor_state_success", "CHECK (last_success IS NULL OR last_success IN (0, 1))"},
	{"v2_client_entry_monitor_state", "chk_v2_client_entry_monitor_state_latency", "CHECK (last_latency_ms IS NULL OR last_latency_ms >= 0)"},
	{"v2_client_entry_monitor_state", "chk_v2_client_entry_monitor_state_streaks", "CHECK (consecutive_success >= 0 AND consecutive_failure >= 0)"},
	{"v2_client_entry_monitor_event", "fk_v2_client_entry_monitor_event_target", "FOREIGN KEY (target_id) REFERENCES v2_client_entry_monitor_target(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_event", "fk_v2_client_entry_monitor_event_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_event", "chk_v2_client_entry_monitor_event_type", "CHECK (btrim(event_type) <> '')"},
	{"v2_client_entry_monitor_event", "chk_v2_client_entry_monitor_event_attempts", "CHECK (notify_attempts >= 0)"},
	{"v2_client_entry_monitor_event_delivery", "fk_v2_client_entry_monitor_event_delivery_event", "FOREIGN KEY (event_id) REFERENCES v2_client_entry_monitor_event(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_event_delivery", "uniq_v2_client_entry_monitor_event_delivery", "UNIQUE (event_id, chat_id)"},
	{"v2_client_entry_monitor_event_delivery", "chk_v2_client_entry_monitor_event_delivery_attempts", "CHECK (attempts >= 0)"},
	{"v2_client_entry_monitor_event_delivery", "chk_v2_client_entry_monitor_event_delivery_next", "CHECK (next_attempt_at >= 0)"},
	{"v2_client_entry_monitor_run", "fk_v2_client_entry_monitor_run_user", "FOREIGN KEY (requested_by_user_id) REFERENCES v2_user(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_policies", "CHECK (jsonb_typeof(policy_ids) = 'array')"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_expected_pairs", "CHECK (jsonb_typeof(expected_pairs) = 'array')"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_status", "CHECK (btrim(status) <> '')"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_counts", "CHECK (expected_results >= 0 AND received_results >= 0)"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_attempts", "CHECK (notify_attempts >= 0)"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_request_key", "CHECK (request_key IS NULL OR btrim(request_key) <> '')"},
	{"v2_client_entry_monitor_run", "uniq_v2_client_entry_monitor_run_request_key", "UNIQUE (request_key)"},
	{"v2_client_entry_monitor_run_result", "fk_v2_client_entry_monitor_run_result_run", "FOREIGN KEY (run_id) REFERENCES v2_client_entry_monitor_run(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_run_result", "uniq_v2_client_entry_monitor_run_result", "UNIQUE (run_id, target_id, probe_id)"},
	{"v2_client_entry_monitor_run_result", "chk_v2_client_entry_monitor_run_result_success", "CHECK (success IN (0, 1))"},
	{"v2_client_entry_monitor_run_result", "chk_v2_client_entry_monitor_run_result_latency", "CHECK (latency_ms IS NULL OR latency_ms >= 0)"},
	{"v2_client_entry_monitor_run_result", "chk_v2_client_entry_monitor_run_result_port", "CHECK (port BETWEEN 1 AND 65535)"},
	{"v2_client_entry_monitor_result_inbox", "fk_v2_client_entry_monitor_inbox_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_result_inbox", "fk_v2_client_entry_monitor_inbox_target", "FOREIGN KEY (target_id) REFERENCES v2_client_entry_monitor_target(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_result_inbox", "fk_v2_client_entry_monitor_inbox_run", "FOREIGN KEY (run_id) REFERENCES v2_client_entry_monitor_run(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_result_inbox", "uniq_v2_client_entry_monitor_inbox_result", "UNIQUE (probe_id, result_id)"},
	{"v2_client_entry_monitor_result_inbox", "chk_v2_client_entry_monitor_inbox_result_id", "CHECK (btrim(result_id) <> '')"},
}

var clientEntryMonitorIndexStatements = []string{
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_enabled ON v2_client_entry_monitor(enabled, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_target_sort ON v2_client_entry_monitor_target(monitor_id, sort, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_probe_probe ON v2_client_entry_monitor_probe(probe_id, monitor_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_state_probe ON v2_client_entry_monitor_state(probe_id, target_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_state_reported ON v2_client_entry_monitor_state(last_reported_at, target_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_notify_due ON v2_client_entry_monitor_event(notified_at, notify_next_attempt_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_monitor_created ON v2_client_entry_monitor_event(monitor_id, created_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_created ON v2_client_entry_monitor_event(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_delivery_due ON v2_client_entry_monitor_event_delivery(event_id, delivered_at, next_attempt_at, chat_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_status ON v2_client_entry_monitor_run(status, created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_notify ON v2_client_entry_monitor_run(notified_at, notify_next_attempt_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_created ON v2_client_entry_monitor_run(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_result_reported ON v2_client_entry_monitor_run_result(reported_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_result_created ON v2_client_entry_monitor_run_result(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_inbox_target ON v2_client_entry_monitor_result_inbox(target_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_inbox_run ON v2_client_entry_monitor_result_inbox(run_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_inbox_created ON v2_client_entry_monitor_result_inbox(created_at, id)`,
}
