package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

func ensureClientEntryCollectionSchema(ctx context.Context, db *sql.DB) error {
	for _, stmt := range []string{
		`CREATE TABLE IF NOT EXISTS v2_client_entry_collection (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(255) NOT NULL,
 entry_host varchar(255) NOT NULL,
 version BIGINT NOT NULL DEFAULT 1,
 created_at BIGINT NOT NULL,
 updated_at BIGINT NOT NULL
 )`,
		`CREATE TABLE IF NOT EXISTS v2_client_entry_collection_member (
 collection_id BIGINT NOT NULL REFERENCES v2_client_entry_collection(id) ON DELETE CASCADE,
 policy_id INTEGER UNIQUE REFERENCES v2_client_entry_user_policy(id) ON DELETE CASCADE,
 split_group_id BIGINT UNIQUE REFERENCES v2_client_entry_user_policy_split_group(id) ON DELETE CASCADE,
 CONSTRAINT ck_client_entry_collection_one_member CHECK ((policy_id IS NULL) <> (split_group_id IS NULL))
 )`,
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_collection_member_collection ON v2_client_entry_collection_member(collection_id)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry collection schema: %w", err)
		}
	}
	return nil
}
