package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

// EnsureClientEntryMonitorSchema creates persistence for TCP monitoring of
// client-entry policies. The monitor is deliberately separate from DNS
// failover state: an unhealthy client entry can notify operators, but cannot
// accidentally trigger a DNS mutation.
func EnsureClientEntryMonitorSchema(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db is nil")
	}

	for _, stmt := range clientEntryMonitorTableStatements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry monitor table: %w", err)
		}
	}
	for _, stmt := range clientEntryMonitorMigrationStatements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("migrate client entry monitor schema: %w", err)
		}
	}

	for _, constraint := range clientEntryMonitorConstraints {
		stmt := fmt.Sprintf(`DO $client_entry_monitor$
BEGIN
ALTER TABLE %s ADD CONSTRAINT %s %s;
EXCEPTION
WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_monitor$;`, constraint.table, constraint.name, constraint.definition)
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry monitor constraint %s: %w", constraint.name, err)
		}
	}

	for _, stmt := range clientEntryMonitorIndexStatements {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry monitor index: %w", err)
		}
	}
	if _, err := db.ExecContext(ctx, clientEntryMonitorConfigSeedStatement); err != nil {
		return fmt.Errorf("ensure client entry monitor config singleton: %w", err)
	}
	return nil
}

var clientEntryMonitorTableStatements = []string{
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_config (
id SMALLINT NOT NULL,
revision BIGINT NOT NULL DEFAULT 1,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
policy_id INTEGER NOT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
check_interval_sec INTEGER NOT NULL DEFAULT 30,
tcp_timeout_ms INTEGER NOT NULL DEFAULT 5000,
failure_threshold INTEGER NOT NULL DEFAULT 3,
success_threshold INTEGER NOT NULL DEFAULT 2,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_target (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
monitor_id BIGINT NOT NULL,
source_key varchar(255) NOT NULL,
name varchar(255) NOT NULL DEFAULT '',
host varchar(255) NOT NULL,
port INTEGER NOT NULL,
generation BIGINT NOT NULL DEFAULT 1,
auto_split_enabled SMALLINT NOT NULL DEFAULT 0,
sort INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_probe (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
monitor_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_state (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
target_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
last_success SMALLINT DEFAULT NULL,
last_latency_ms INTEGER DEFAULT NULL,
last_error text NOT NULL DEFAULT '',
last_resolved_ip varchar(128) NOT NULL DEFAULT '',
consecutive_success INTEGER NOT NULL DEFAULT 0,
consecutive_failure INTEGER NOT NULL DEFAULT 0,
last_reported_at BIGINT DEFAULT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_event (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
monitor_id BIGINT NOT NULL,
target_id BIGINT DEFAULT NULL,
probe_id BIGINT DEFAULT NULL,
event_type varchar(32) NOT NULL,
message text NOT NULL DEFAULT '',
details text NOT NULL DEFAULT '{}',
notified_at BIGINT DEFAULT NULL,
notify_attempts INTEGER NOT NULL DEFAULT 0,
notify_next_attempt_at BIGINT NOT NULL DEFAULT 0,
last_notify_error text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_event_delivery (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
event_id BIGINT NOT NULL,
chat_id BIGINT NOT NULL,
delivered_at BIGINT DEFAULT NULL,
attempts INTEGER NOT NULL DEFAULT 0,
next_attempt_at BIGINT NOT NULL DEFAULT 0,
last_error text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_run (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
requested_by_user_id INTEGER DEFAULT NULL,
request_chat_id BIGINT DEFAULT NULL,
request_key varchar(255) DEFAULT NULL,
progress_message_id BIGINT DEFAULT NULL,
policy_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
expected_pairs jsonb NOT NULL DEFAULT '[]'::jsonb,
status varchar(32) NOT NULL DEFAULT 'pending',
expected_results INTEGER NOT NULL DEFAULT 0,
received_results INTEGER NOT NULL DEFAULT 0,
progress_reported_results INTEGER NOT NULL DEFAULT -1,
progress_reported_status varchar(32) NOT NULL DEFAULT '',
progress_attempts INTEGER NOT NULL DEFAULT 0,
progress_next_attempt_at BIGINT NOT NULL DEFAULT 0,
progress_last_error text NOT NULL DEFAULT '',
started_at BIGINT DEFAULT NULL,
completed_at BIGINT DEFAULT NULL,
notified_at BIGINT DEFAULT NULL,
notify_attempts INTEGER NOT NULL DEFAULT 0,
notify_next_attempt_at BIGINT NOT NULL DEFAULT 0,
last_notify_error text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_run_result (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
run_id BIGINT NOT NULL,
policy_id INTEGER NOT NULL DEFAULT 0,
policy_name varchar(255) NOT NULL DEFAULT '',
target_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
target_name varchar(255) NOT NULL DEFAULT '',
host varchar(255) NOT NULL DEFAULT '',
port INTEGER NOT NULL DEFAULT 443,
probe_name varchar(255) NOT NULL DEFAULT '',
success SMALLINT NOT NULL,
latency_ms INTEGER DEFAULT NULL,
error text NOT NULL DEFAULT '',
resolved_ip varchar(128) NOT NULL DEFAULT '',
reported_at BIGINT NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_monitor_result_inbox (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
probe_id BIGINT NOT NULL,
target_id BIGINT DEFAULT NULL,
run_id BIGINT DEFAULT NULL,
result_id varchar(128) NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_backup_ip (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name varchar(255) NOT NULL DEFAULT '',
ip varchar(128) NOT NULL,
port INTEGER NOT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
check_interval_sec INTEGER NOT NULL DEFAULT 30,
tcp_timeout_ms INTEGER NOT NULL DEFAULT 3000,
generation BIGINT NOT NULL DEFAULT 1,
sort INTEGER NOT NULL DEFAULT 0,
quarantine_until BIGINT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_backup_ip_state (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
backup_ip_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
last_success SMALLINT DEFAULT NULL,
last_latency_ms INTEGER DEFAULT NULL,
last_error text NOT NULL DEFAULT '',
consecutive_success INTEGER NOT NULL DEFAULT 0,
consecutive_failure INTEGER NOT NULL DEFAULT 0,
last_reported_at BIGINT DEFAULT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_backup_ip_result_inbox (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
probe_id BIGINT NOT NULL,
backup_ip_id BIGINT DEFAULT NULL,
result_id varchar(128) NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	`CREATE TABLE IF NOT EXISTS v2_client_entry_auto_split_operation (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
monitor_id BIGINT NOT NULL,
target_id BIGINT NOT NULL,
target_generation BIGINT NOT NULL,
policy_id INTEGER NOT NULL,
source_group_id BIGINT NOT NULL,
source_host varchar(255) NOT NULL,
trigger_probe_id BIGINT DEFAULT NULL,
trigger_result_inbox_id BIGINT DEFAULT NULL,
status varchar(32) NOT NULL DEFAULT 'pending',
backup_ip_a_id BIGINT DEFAULT NULL,
backup_ip_b_id BIGINT DEFAULT NULL,
child_group_a_id BIGINT DEFAULT NULL,
child_group_b_id BIGINT DEFAULT NULL,
attempts INTEGER NOT NULL DEFAULT 0,
next_attempt_at BIGINT NOT NULL DEFAULT 0,
last_error text NOT NULL DEFAULT '',
completed_at BIGINT DEFAULT NULL,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
}

var clientEntryMonitorMigrationStatements = []string{
	`DO $client_entry_monitor_timeout$
BEGIN
IF EXISTS (
	SELECT 1
	FROM pg_attribute attribute
	JOIN pg_attrdef default_value
	  ON default_value.adrelid = attribute.attrelid
	 AND default_value.adnum = attribute.attnum
	WHERE attribute.attrelid = 'v2_client_entry_monitor'::regclass
	  AND attribute.attname = 'tcp_timeout_ms'
	  AND pg_get_expr(default_value.adbin, default_value.adrelid) IN ('3000', '3000::integer')
) THEN
	UPDATE v2_client_entry_monitor SET tcp_timeout_ms = 5000 WHERE tcp_timeout_ms = 3000;
END IF;
ALTER TABLE v2_client_entry_monitor ALTER COLUMN tcp_timeout_ms SET DEFAULT 5000;
END
$client_entry_monitor_timeout$;`,
	`ALTER TABLE v2_client_entry_monitor ADD COLUMN IF NOT EXISTS failure_threshold INTEGER NOT NULL DEFAULT 3`,
	`ALTER TABLE v2_client_entry_monitor ADD COLUMN IF NOT EXISTS success_threshold INTEGER NOT NULL DEFAULT 2`,
	`ALTER TABLE v2_client_entry_monitor_event ADD COLUMN IF NOT EXISTS notify_next_attempt_at BIGINT NOT NULL DEFAULT 0`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS request_key varchar(255) DEFAULT NULL`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS expected_pairs jsonb NOT NULL DEFAULT '[]'::jsonb`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS progress_message_id BIGINT DEFAULT NULL`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS progress_reported_results INTEGER NOT NULL DEFAULT -1`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS progress_reported_status varchar(32) NOT NULL DEFAULT ''`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS progress_attempts INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS progress_next_attempt_at BIGINT NOT NULL DEFAULT 0`,
	`ALTER TABLE v2_client_entry_monitor_run ADD COLUMN IF NOT EXISTS progress_last_error text NOT NULL DEFAULT ''`,
	`ALTER TABLE v2_client_entry_monitor_target ADD COLUMN IF NOT EXISTS generation BIGINT NOT NULL DEFAULT 1`,
	`ALTER TABLE v2_client_entry_monitor_target ADD COLUMN IF NOT EXISTS auto_split_enabled SMALLINT NOT NULL DEFAULT 0`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS target_name varchar(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS host varchar(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS port INTEGER NOT NULL DEFAULT 443`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS probe_name varchar(255) NOT NULL DEFAULT ''`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS policy_id INTEGER NOT NULL DEFAULT 0`,
	`ALTER TABLE v2_client_entry_monitor_run_result ADD COLUMN IF NOT EXISTS policy_name varchar(255) NOT NULL DEFAULT ''`,
	`UPDATE v2_client_entry_monitor_run_result result
SET policy_id = monitor.policy_id,
	policy_name = policy.name
FROM v2_client_entry_monitor_target target
JOIN v2_client_entry_monitor monitor ON monitor.id = target.monitor_id
JOIN v2_client_entry_user_policy policy ON policy.id = monitor.policy_id
WHERE result.target_id = target.id
  AND (result.policy_id = 0 OR (btrim(result.policy_name) = '' AND btrim(policy.name) <> ''))`,
}

const clientEntryMonitorConfigSeedStatement = `INSERT INTO v2_client_entry_monitor_config (id, revision, updated_at)
VALUES (1, 1, 0)
ON CONFLICT (id) DO NOTHING`

var clientEntryMonitorConstraints = []struct {
	table      string
	name       string
	definition string
}{
	{"v2_client_entry_monitor_config", "chk_v2_client_entry_monitor_config_singleton", "CHECK (id = 1)"},
	{"v2_client_entry_monitor_config", "chk_v2_client_entry_monitor_config_revision", "CHECK (revision > 0)"},
	{"v2_client_entry_monitor", "fk_v2_client_entry_monitor_policy", "FOREIGN KEY (policy_id) REFERENCES v2_client_entry_user_policy(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor", "uniq_v2_client_entry_monitor_policy", "UNIQUE (policy_id)"},
	{"v2_client_entry_monitor", "chk_v2_client_entry_monitor_enabled", "CHECK (enabled IN (0, 1))"},
	{"v2_client_entry_monitor", "chk_v2_client_entry_monitor_timing", "CHECK (check_interval_sec > 0 AND tcp_timeout_ms > 0)"},
	{"v2_client_entry_monitor", "chk_v2_client_entry_monitor_thresholds", "CHECK (failure_threshold BETWEEN 2 AND 10 AND success_threshold BETWEEN 1 AND 10)"},
	{"v2_client_entry_monitor_target", "fk_v2_client_entry_monitor_target_monitor", "FOREIGN KEY (monitor_id) REFERENCES v2_client_entry_monitor(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_target", "uniq_v2_client_entry_monitor_target_source", "UNIQUE (monitor_id, source_key)"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_source", "CHECK (btrim(source_key) <> '')"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_host", "CHECK (btrim(host) <> '')"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_port", "CHECK (port BETWEEN 1 AND 65535)"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_generation", "CHECK (generation > 0)"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_auto_split", "CHECK (auto_split_enabled IN (0, 1))"},
	{"v2_client_entry_monitor_target", "chk_v2_client_entry_monitor_target_sort", "CHECK (sort >= 0)"},
	{"v2_client_entry_monitor_probe", "fk_v2_client_entry_monitor_probe_monitor", "FOREIGN KEY (monitor_id) REFERENCES v2_client_entry_monitor(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_probe", "fk_v2_client_entry_monitor_probe_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_probe", "uniq_v2_client_entry_monitor_probe", "UNIQUE (monitor_id, probe_id)"},
	{"v2_client_entry_monitor_state", "fk_v2_client_entry_monitor_state_target", "FOREIGN KEY (target_id) REFERENCES v2_client_entry_monitor_target(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_state", "fk_v2_client_entry_monitor_state_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_state", "uniq_v2_client_entry_monitor_state", "UNIQUE (target_id, probe_id)"},
	{"v2_client_entry_monitor_state", "chk_v2_client_entry_monitor_state_success", "CHECK (last_success IS NULL OR last_success IN (0, 1))"},
	{"v2_client_entry_monitor_state", "chk_v2_client_entry_monitor_state_latency", "CHECK (last_latency_ms IS NULL OR last_latency_ms >= 0)"},
	{"v2_client_entry_monitor_state", "chk_v2_client_entry_monitor_state_streaks", "CHECK (consecutive_success >= 0 AND consecutive_failure >= 0)"},
	{"v2_client_entry_monitor_event", "fk_v2_client_entry_monitor_event_target", "FOREIGN KEY (target_id) REFERENCES v2_client_entry_monitor_target(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_event", "fk_v2_client_entry_monitor_event_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_event", "chk_v2_client_entry_monitor_event_type", "CHECK (btrim(event_type) <> '')"},
	{"v2_client_entry_monitor_event", "chk_v2_client_entry_monitor_event_attempts", "CHECK (notify_attempts >= 0)"},
	{"v2_client_entry_monitor_event_delivery", "fk_v2_client_entry_monitor_event_delivery_event", "FOREIGN KEY (event_id) REFERENCES v2_client_entry_monitor_event(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_event_delivery", "uniq_v2_client_entry_monitor_event_delivery", "UNIQUE (event_id, chat_id)"},
	{"v2_client_entry_monitor_event_delivery", "chk_v2_client_entry_monitor_event_delivery_attempts", "CHECK (attempts >= 0)"},
	{"v2_client_entry_monitor_event_delivery", "chk_v2_client_entry_monitor_event_delivery_next", "CHECK (next_attempt_at >= 0)"},
	{"v2_client_entry_monitor_run", "fk_v2_client_entry_monitor_run_user", "FOREIGN KEY (requested_by_user_id) REFERENCES v2_user(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_policies", "CHECK (jsonb_typeof(policy_ids) = 'array')"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_expected_pairs", "CHECK (jsonb_typeof(expected_pairs) = 'array')"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_status", "CHECK (btrim(status) <> '')"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_counts", "CHECK (expected_results >= 0 AND received_results >= 0)"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_progress_results", "CHECK (progress_reported_results >= -1)"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_progress_attempts", "CHECK (progress_attempts >= 0)"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_progress_next", "CHECK (progress_next_attempt_at >= 0)"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_attempts", "CHECK (notify_attempts >= 0)"},
	{"v2_client_entry_monitor_run", "chk_v2_client_entry_monitor_run_request_key", "CHECK (request_key IS NULL OR btrim(request_key) <> '')"},
	{"v2_client_entry_monitor_run", "uniq_v2_client_entry_monitor_run_request_key", "UNIQUE (request_key)"},
	{"v2_client_entry_monitor_run_result", "fk_v2_client_entry_monitor_run_result_run", "FOREIGN KEY (run_id) REFERENCES v2_client_entry_monitor_run(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_run_result", "uniq_v2_client_entry_monitor_run_result", "UNIQUE (run_id, target_id, probe_id)"},
	{"v2_client_entry_monitor_run_result", "chk_v2_client_entry_monitor_run_result_success", "CHECK (success IN (0, 1))"},
	{"v2_client_entry_monitor_run_result", "chk_v2_client_entry_monitor_run_result_latency", "CHECK (latency_ms IS NULL OR latency_ms >= 0)"},
	{"v2_client_entry_monitor_run_result", "chk_v2_client_entry_monitor_run_result_port", "CHECK (port BETWEEN 1 AND 65535)"},
	{"v2_client_entry_monitor_result_inbox", "fk_v2_client_entry_monitor_inbox_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_monitor_result_inbox", "fk_v2_client_entry_monitor_inbox_target", "FOREIGN KEY (target_id) REFERENCES v2_client_entry_monitor_target(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_result_inbox", "fk_v2_client_entry_monitor_inbox_run", "FOREIGN KEY (run_id) REFERENCES v2_client_entry_monitor_run(id) ON DELETE SET NULL"},
	{"v2_client_entry_monitor_result_inbox", "uniq_v2_client_entry_monitor_inbox_result", "UNIQUE (probe_id, result_id)"},
	{"v2_client_entry_monitor_result_inbox", "chk_v2_client_entry_monitor_inbox_result_id", "CHECK (btrim(result_id) <> '')"},
	{"v2_client_entry_backup_ip", "uniq_v2_client_entry_backup_ip_value", "UNIQUE (ip)"},
	{"v2_client_entry_backup_ip", "chk_v2_client_entry_backup_ip_value", "CHECK (btrim(ip) <> '')"},
	{"v2_client_entry_backup_ip", "chk_v2_client_entry_backup_ip_port", "CHECK (port BETWEEN 1 AND 65535)"},
	{"v2_client_entry_backup_ip", "chk_v2_client_entry_backup_ip_enabled", "CHECK (enabled IN (0, 1))"},
	{"v2_client_entry_backup_ip", "chk_v2_client_entry_backup_ip_timing", "CHECK (check_interval_sec > 0 AND tcp_timeout_ms > 0)"},
	{"v2_client_entry_backup_ip", "chk_v2_client_entry_backup_ip_generation", "CHECK (generation > 0)"},
	{"v2_client_entry_backup_ip", "chk_v2_client_entry_backup_ip_sort", "CHECK (sort >= 0)"},
	{"v2_client_entry_backup_ip", "chk_v2_client_entry_backup_ip_quarantine", "CHECK (quarantine_until >= 0)"},
	{"v2_client_entry_backup_ip_state", "fk_v2_client_entry_backup_ip_state_ip", "FOREIGN KEY (backup_ip_id) REFERENCES v2_client_entry_backup_ip(id) ON DELETE CASCADE"},
	{"v2_client_entry_backup_ip_state", "fk_v2_client_entry_backup_ip_state_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_backup_ip_state", "uniq_v2_client_entry_backup_ip_state", "UNIQUE (backup_ip_id, probe_id)"},
	{"v2_client_entry_backup_ip_state", "chk_v2_client_entry_backup_ip_state_success", "CHECK (last_success IS NULL OR last_success IN (0, 1))"},
	{"v2_client_entry_backup_ip_state", "chk_v2_client_entry_backup_ip_state_latency", "CHECK (last_latency_ms IS NULL OR last_latency_ms >= 0)"},
	{"v2_client_entry_backup_ip_state", "chk_v2_client_entry_backup_ip_state_streaks", "CHECK (consecutive_success >= 0 AND consecutive_failure >= 0)"},
	{"v2_client_entry_backup_ip_result_inbox", "fk_v2_client_entry_backup_ip_inbox_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_client_entry_backup_ip_result_inbox", "fk_v2_client_entry_backup_ip_inbox_ip", "FOREIGN KEY (backup_ip_id) REFERENCES v2_client_entry_backup_ip(id) ON DELETE SET NULL"},
	{"v2_client_entry_backup_ip_result_inbox", "uniq_v2_client_entry_backup_ip_inbox_result", "UNIQUE (probe_id, result_id)"},
	{"v2_client_entry_backup_ip_result_inbox", "chk_v2_client_entry_backup_ip_inbox_result_id", "CHECK (btrim(result_id) <> '')"},
	{"v2_client_entry_auto_split_operation", "chk_v2_client_entry_auto_split_status", "CHECK (status IN ('pending', 'succeeded', 'cancelled'))"},
	{"v2_client_entry_auto_split_operation", "chk_v2_client_entry_auto_split_generation", "CHECK (target_generation > 0)"},
	{"v2_client_entry_auto_split_operation", "chk_v2_client_entry_auto_split_attempts", "CHECK (attempts >= 0)"},
	{"v2_client_entry_auto_split_operation", "chk_v2_client_entry_auto_split_next", "CHECK (next_attempt_at >= 0)"},
	{"v2_client_entry_auto_split_operation", "chk_v2_client_entry_auto_split_source", "CHECK (btrim(source_host) <> '')"},
}

var clientEntryMonitorIndexStatements = []string{
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_enabled ON v2_client_entry_monitor(enabled, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_target_sort ON v2_client_entry_monitor_target(monitor_id, sort, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_probe_probe ON v2_client_entry_monitor_probe(probe_id, monitor_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_state_probe ON v2_client_entry_monitor_state(probe_id, target_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_state_reported ON v2_client_entry_monitor_state(last_reported_at, target_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_notify_due ON v2_client_entry_monitor_event(notified_at, notify_next_attempt_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_monitor_created ON v2_client_entry_monitor_event(monitor_id, created_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_created ON v2_client_entry_monitor_event(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_event_delivery_due ON v2_client_entry_monitor_event_delivery(event_id, delivered_at, next_attempt_at, chat_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_status ON v2_client_entry_monitor_run(status, created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_notify ON v2_client_entry_monitor_run(notified_at, notify_next_attempt_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_progress_due ON v2_client_entry_monitor_run(progress_message_id, progress_next_attempt_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_created ON v2_client_entry_monitor_run(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_result_reported ON v2_client_entry_monitor_run_result(reported_at DESC, id DESC)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_run_result_created ON v2_client_entry_monitor_run_result(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_inbox_target ON v2_client_entry_monitor_result_inbox(target_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_inbox_run ON v2_client_entry_monitor_result_inbox(run_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_monitor_inbox_created ON v2_client_entry_monitor_result_inbox(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_backup_ip_order ON v2_client_entry_backup_ip(sort, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_backup_ip_available ON v2_client_entry_backup_ip(enabled, quarantine_until, sort, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_backup_ip_state_probe ON v2_client_entry_backup_ip_state(probe_id, backup_ip_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_backup_ip_state_reported ON v2_client_entry_backup_ip_state(last_reported_at, backup_ip_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_backup_ip_inbox_ip ON v2_client_entry_backup_ip_result_inbox(backup_ip_id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_backup_ip_inbox_created ON v2_client_entry_backup_ip_result_inbox(created_at, id)`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_auto_split_due ON v2_client_entry_auto_split_operation(status, next_attempt_at, id)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS idx_v2_client_entry_auto_split_pending_group_unique ON v2_client_entry_auto_split_operation(policy_id, source_group_id) WHERE status = 'pending'`,
	`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_auto_split_created ON v2_client_entry_auto_split_operation(created_at, id)`,
}
