package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

// EnsureDNSFailoverSchema creates the persistent state used by DNS failover.
// Every statement is safe to execute more than once so callers can initialize
// the schema lazily without coordinating across processes.
func EnsureDNSFailoverSchema(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db is nil")
	}

	for _, stmt := range []string{
		`CREATE TABLE IF NOT EXISTS v2_dns_probe (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name varchar(255) NOT NULL,
token_hash char(64) NOT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
version varchar(64) NOT NULL DEFAULT '',
arch varchar(32) NOT NULL DEFAULT '',
public_ip varchar(128) NOT NULL DEFAULT '',
last_heartbeat_at BIGINT DEFAULT NULL,
prewarm_count INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_probe_token_hash UNIQUE (token_hash)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_group (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name varchar(255) NOT NULL DEFAULT '',
domain_id BIGINT NOT NULL,
domain varchar(255) NOT NULL,
record_id BIGINT NOT NULL,
subdomain varchar(255) NOT NULL,
record_line_id varchar(255) NOT NULL DEFAULT '',
record_line_name varchar(255) NOT NULL DEFAULT '',
ttl INTEGER NOT NULL DEFAULT 600,
mx INTEGER NOT NULL DEFAULT 0,
weight INTEGER DEFAULT NULL,
current_target_id BIGINT DEFAULT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
auto_failback SMALLINT NOT NULL DEFAULT 1,
check_interval_sec INTEGER NOT NULL DEFAULT 30,
tcp_timeout_ms INTEGER NOT NULL DEFAULT 3000,
failure_threshold INTEGER NOT NULL DEFAULT 3,
success_threshold INTEGER NOT NULL DEFAULT 6,
single_probe_failure_threshold INTEGER NOT NULL DEFAULT 5,
single_probe_success_threshold INTEGER NOT NULL DEFAULT 8,
probe_offline_sec INTEGER NOT NULL DEFAULT 90,
cooldown_sec INTEGER NOT NULL DEFAULT 300,
last_switch_at BIGINT DEFAULT NULL,
last_switch_reason text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_failover_group_record UNIQUE (domain_id, record_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_target (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
group_id BIGINT NOT NULL,
sort INTEGER NOT NULL DEFAULT 0,
name varchar(255) NOT NULL DEFAULT '',
dns_type varchar(8) NOT NULL,
dns_value varchar(1024) NOT NULL,
check_host varchar(255) NOT NULL,
check_port INTEGER NOT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT chk_v2_dns_failover_target_type CHECK (dns_type IN ('A', 'AAAA', 'CNAME')),
CONSTRAINT uniq_v2_dns_failover_target_sort UNIQUE (group_id, sort)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_group_probe (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
group_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_failover_group_probe UNIQUE (group_id, probe_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_probe_target_state (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
probe_id BIGINT NOT NULL,
target_id BIGINT NOT NULL,
last_success SMALLINT DEFAULT NULL,
last_latency_ms INTEGER DEFAULT NULL,
last_error text NOT NULL DEFAULT '',
consecutive_success INTEGER NOT NULL DEFAULT 0,
consecutive_failure INTEGER NOT NULL DEFAULT 0,
last_reported_at BIGINT DEFAULT NULL,
warmed_up SMALLINT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_probe_target_state UNIQUE (probe_id, target_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_probe_result_inbox (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
probe_id BIGINT NOT NULL,
target_id BIGINT NOT NULL,
result_id varchar(128) NOT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_probe_result_inbox_result UNIQUE (probe_id, result_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_event (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
group_id BIGINT NOT NULL,
probe_id BIGINT DEFAULT NULL,
target_id BIGINT DEFAULT NULL,
event_type varchar(32) NOT NULL,
message text NOT NULL DEFAULT '',
details text NOT NULL DEFAULT '{}',
dedupe_key varchar(255) NOT NULL DEFAULT '',
notified_at BIGINT DEFAULT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure DNS failover table: %w", err)
		}
	}

	for _, constraint := range dnsFailoverConstraints {
		stmt := fmt.Sprintf(`DO $dns_failover$
BEGIN
ALTER TABLE %s ADD CONSTRAINT %s %s;
EXCEPTION
WHEN duplicate_object THEN NULL;
END
$dns_failover$;`, constraint.table, constraint.name, constraint.definition)
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure DNS failover constraint %s: %w", constraint.name, err)
		}
	}

	for _, stmt := range []string{
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_probe_enabled_heartbeat ON v2_dns_probe(enabled, last_heartbeat_at)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_group_enabled ON v2_dns_failover_group(enabled)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_target_group_sort ON v2_dns_failover_target(group_id, enabled, sort)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_group_probe_probe ON v2_dns_failover_group_probe(probe_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_probe_target_state_target ON v2_dns_probe_target_state(target_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_probe_result_inbox_target ON v2_dns_probe_result_inbox(target_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_event_group_created ON v2_dns_failover_event(group_id, created_at DESC)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure DNS failover index: %w", err)
		}
	}

	return nil
}

var dnsFailoverConstraints = []struct {
	table      string
	name       string
	definition string
}{
	{"v2_dns_probe", "chk_v2_dns_probe_enabled", "CHECK (enabled IN (0, 1))"},
	{"v2_dns_probe", "chk_v2_dns_probe_prewarm", "CHECK (prewarm_count >= 0)"},
	{"v2_dns_failover_group", "chk_v2_dns_failover_group_flags", "CHECK (enabled IN (0, 1) AND auto_failback IN (0, 1))"},
	{"v2_dns_failover_group", "chk_v2_dns_failover_group_timing", "CHECK (check_interval_sec > 0 AND tcp_timeout_ms > 0 AND probe_offline_sec > 0 AND cooldown_sec >= 0)"},
	{"v2_dns_failover_group", "chk_v2_dns_failover_group_thresholds", "CHECK (failure_threshold > 0 AND success_threshold > 0 AND single_probe_failure_threshold > failure_threshold AND single_probe_success_threshold > success_threshold)"},
	{"v2_dns_failover_group", "chk_v2_dns_failover_group_dns_values", "CHECK (ttl >= 0 AND mx >= 0 AND (weight IS NULL OR weight >= 0))"},
	{"v2_dns_failover_target", "fk_v2_dns_failover_target_group", "FOREIGN KEY (group_id) REFERENCES v2_dns_failover_group(id) ON DELETE CASCADE"},
	{"v2_dns_failover_target", "uniq_v2_dns_failover_target_group_id", "UNIQUE (group_id, id)"},
	{"v2_dns_failover_target", "chk_v2_dns_failover_target_type", "CHECK (dns_type IN ('A', 'AAAA', 'CNAME'))"},
	{"v2_dns_failover_target", "chk_v2_dns_failover_target_enabled", "CHECK (enabled IN (0, 1))"},
	{"v2_dns_failover_target", "chk_v2_dns_failover_target_sort", "CHECK (sort >= 0)"},
	{"v2_dns_failover_target", "chk_v2_dns_failover_target_port", "CHECK (check_port BETWEEN 1 AND 65535)"},
	{"v2_dns_failover_group", "fk_v2_dns_failover_group_current_target", "FOREIGN KEY (id, current_target_id) REFERENCES v2_dns_failover_target(group_id, id) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED"},
	{"v2_dns_failover_group_probe", "fk_v2_dns_failover_group_probe_group", "FOREIGN KEY (group_id) REFERENCES v2_dns_failover_group(id) ON DELETE CASCADE"},
	{"v2_dns_failover_group_probe", "fk_v2_dns_failover_group_probe_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_dns_probe_target_state", "fk_v2_dns_probe_target_state_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_dns_probe_target_state", "fk_v2_dns_probe_target_state_target", "FOREIGN KEY (target_id) REFERENCES v2_dns_failover_target(id) ON DELETE CASCADE"},
	{"v2_dns_probe_target_state", "chk_v2_dns_probe_target_state_flags", "CHECK ((last_success IS NULL OR last_success IN (0, 1)) AND warmed_up IN (0, 1))"},
	{"v2_dns_probe_target_state", "chk_v2_dns_probe_target_state_streaks", "CHECK (consecutive_success >= 0 AND consecutive_failure >= 0)"},
	{"v2_dns_probe_target_state", "chk_v2_dns_probe_target_state_latency", "CHECK (last_latency_ms IS NULL OR last_latency_ms >= 0)"},
	{"v2_dns_probe_result_inbox", "fk_v2_dns_probe_result_inbox_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE CASCADE"},
	{"v2_dns_probe_result_inbox", "fk_v2_dns_probe_result_inbox_target", "FOREIGN KEY (target_id) REFERENCES v2_dns_failover_target(id) ON DELETE CASCADE"},
	{"v2_dns_probe_result_inbox", "uniq_v2_dns_probe_result_inbox_result", "UNIQUE (probe_id, result_id)"},
	{"v2_dns_probe_result_inbox", "chk_v2_dns_probe_result_inbox_result_id", "CHECK (btrim(result_id) <> '')"},
	{"v2_dns_failover_event", "fk_v2_dns_failover_event_group", "FOREIGN KEY (group_id) REFERENCES v2_dns_failover_group(id) ON DELETE CASCADE"},
	{"v2_dns_failover_event", "fk_v2_dns_failover_event_probe", "FOREIGN KEY (probe_id) REFERENCES v2_dns_probe(id) ON DELETE SET NULL"},
	{"v2_dns_failover_event", "fk_v2_dns_failover_event_target", "FOREIGN KEY (target_id) REFERENCES v2_dns_failover_target(id) ON DELETE SET NULL"},
	{"v2_dns_failover_event", "chk_v2_dns_failover_event_type", "CHECK (btrim(event_type) <> '')"},
}
