package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

// EnsureDNSFailoverSchema creates the persistent state used by DNS failover.
// Every statement is safe to execute more than once so callers can initialize
// the schema lazily without coordinating across processes.
func EnsureDNSFailoverSchema(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db is nil")
	}

	for _, stmt := range []string{
		`CREATE TABLE IF NOT EXISTS v2_dns_probe (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name varchar(255) NOT NULL,
token_hash char(64) NOT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
version varchar(64) NOT NULL DEFAULT '',
arch varchar(32) NOT NULL DEFAULT '',
public_ip varchar(128) NOT NULL DEFAULT '',
last_heartbeat_at BIGINT DEFAULT NULL,
prewarm_count INTEGER NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_probe_token_hash UNIQUE (token_hash)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_group (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name varchar(255) NOT NULL DEFAULT '',
domain_id BIGINT NOT NULL,
domain varchar(255) NOT NULL,
record_id BIGINT NOT NULL,
subdomain varchar(255) NOT NULL,
record_line_id varchar(255) NOT NULL DEFAULT '',
record_line_name varchar(255) NOT NULL DEFAULT '',
ttl INTEGER NOT NULL DEFAULT 600,
mx INTEGER NOT NULL DEFAULT 0,
weight INTEGER DEFAULT NULL,
current_target_id BIGINT DEFAULT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
auto_failback SMALLINT NOT NULL DEFAULT 1,
check_interval_sec INTEGER NOT NULL DEFAULT 30,
tcp_timeout_ms INTEGER NOT NULL DEFAULT 3000,
failure_threshold INTEGER NOT NULL DEFAULT 3,
success_threshold INTEGER NOT NULL DEFAULT 6,
single_probe_failure_threshold INTEGER NOT NULL DEFAULT 5,
single_probe_success_threshold INTEGER NOT NULL DEFAULT 8,
probe_offline_sec INTEGER NOT NULL DEFAULT 90,
cooldown_sec INTEGER NOT NULL DEFAULT 300,
last_switch_at BIGINT DEFAULT NULL,
last_switch_reason text NOT NULL DEFAULT '',
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_failover_group_record UNIQUE (domain_id, record_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_target (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
group_id BIGINT NOT NULL,
sort INTEGER NOT NULL DEFAULT 0,
name varchar(255) NOT NULL DEFAULT '',
dns_type varchar(8) NOT NULL,
dns_value varchar(1024) NOT NULL,
check_host varchar(255) NOT NULL,
check_port INTEGER NOT NULL,
enabled SMALLINT NOT NULL DEFAULT 1,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT chk_v2_dns_failover_target_type CHECK (dns_type IN ('A', 'AAAA', 'CNAME')),
CONSTRAINT uniq_v2_dns_failover_target_sort UNIQUE (group_id, sort)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_group_probe (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
group_id BIGINT NOT NULL,
probe_id BIGINT NOT NULL,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_failover_group_probe UNIQUE (group_id, probe_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_probe_target_state (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
probe_id BIGINT NOT NULL,
target_id BIGINT NOT NULL,
last_success SMALLINT DEFAULT NULL,
last_latency_ms INTEGER DEFAULT NULL,
last_error text NOT NULL DEFAULT '',
consecutive_success INTEGER NOT NULL DEFAULT 0,
consecutive_failure INTEGER NOT NULL DEFAULT 0,
last_reported_at BIGINT DEFAULT NULL,
warmed_up SMALLINT NOT NULL DEFAULT 0,
created_at BIGINT NOT NULL,
updated_at BIGINT NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_dns_probe_target_state UNIQUE (probe_id, target_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_dns_failover_event (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
group_id BIGINT NOT NULL,
probe_id BIGINT DEFAULT NULL,
target_id BIGINT DEFAULT NULL,
event_type varchar(32) NOT NULL,
message text NOT NULL DEFAULT '',
details text NOT NULL DEFAULT '{}',
dedupe_key varchar(255) NOT NULL DEFAULT '',
notified_at BIGINT DEFAULT NULL,
created_at BIGINT NOT NULL,
PRIMARY KEY (id)
)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure DNS failover table: %w", err)
		}
	}

	for _, stmt := range []string{
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_probe_enabled_heartbeat ON v2_dns_probe(enabled, last_heartbeat_at)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_group_enabled ON v2_dns_failover_group(enabled)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_target_group_sort ON v2_dns_failover_target(group_id, enabled, sort)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_group_probe_probe ON v2_dns_failover_group_probe(probe_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_probe_target_state_target ON v2_dns_probe_target_state(target_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_dns_failover_event_group_created ON v2_dns_failover_event(group_id, created_at DESC)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure DNS failover index: %w", err)
		}
	}

	return nil
}
