package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

// EnsureClientEntrySchema creates the current client-entry tables.  Legacy
// email/server columns are only detected for the one-time updater migration;
// subscription and admin rule paths never read them.
func EnsureClientEntrySchema(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db is nil")
	}

	for _, stmt := range []string{
		`CREATE TABLE IF NOT EXISTS v2_client_entry_group (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
code varchar(64) NOT NULL,
name varchar(255) NOT NULL,
display_name varchar(255) NOT NULL,
strategy varchar(32) NOT NULL,
hide_member_nodes SMALLINT NOT NULL DEFAULT 0,
"show" SMALLINT NOT NULL DEFAULT 1,
remote_enabled SMALLINT NOT NULL DEFAULT 0,
remote_host varchar(255) NOT NULL DEFAULT '',
remote_ssh_port INTEGER NOT NULL DEFAULT 22,
remote_ssh_user varchar(255) NOT NULL DEFAULT '',
remote_ssh_password text NOT NULL DEFAULT '',
remote_group_ref varchar(255) NOT NULL DEFAULT '',
remote_exclude_names text NOT NULL DEFAULT '[]',
remote_refresh_sec INTEGER NOT NULL DEFAULT 300,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_group_code UNIQUE (code)
)`,
		`CREATE TABLE IF NOT EXISTS v2_client_entry_group_member (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
entry_group_id INTEGER NOT NULL DEFAULT 0,
server_type varchar(16) NOT NULL DEFAULT '',
server_id INTEGER NOT NULL DEFAULT 0,
sort INTEGER DEFAULT NULL,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_group_member UNIQUE (entry_group_id, server_type, server_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_client_entry_group_ip (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
entry_group_id INTEGER NOT NULL,
ip varchar(128) NOT NULL,
sort INTEGER DEFAULT NULL,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_group_ip UNIQUE (entry_group_id, ip)
)`,
		`CREATE TABLE IF NOT EXISTS v2_client_entry_user_policy (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name varchar(255) NOT NULL DEFAULT '',
sort INTEGER NOT NULL DEFAULT 0,
action varchar(16) NOT NULL DEFAULT 'override',
conditions text NOT NULL DEFAULT '[]',
entry_host varchar(255) NOT NULL DEFAULT '',
enabled SMALLINT NOT NULL DEFAULT 1,
remarks varchar(255) NOT NULL DEFAULT '',
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_client_entry_user_policy_member (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
policy_id INTEGER NOT NULL,
server_type varchar(16) NOT NULL DEFAULT '',
server_id INTEGER NOT NULL DEFAULT 0,
sort INTEGER DEFAULT NULL,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_user_policy_member UNIQUE (policy_id, server_type, server_id)
)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry table: %w", err)
		}
	}

	for _, item := range []struct {
		table  string
		column string
		stmt   string
	}{
		{"v2_client_entry_group", "remote_enabled", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_enabled SMALLINT NOT NULL DEFAULT 0`},
		{"v2_client_entry_group", "remote_host", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_host varchar(255) NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_ssh_port", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_ssh_port INTEGER NOT NULL DEFAULT 22`},
		{"v2_client_entry_group", "remote_ssh_user", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_ssh_user varchar(255) NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_ssh_password", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_ssh_password text NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_group_ref", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_group_ref varchar(255) NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_exclude_names", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_exclude_names text NOT NULL DEFAULT '[]'`},
		{"v2_client_entry_group", "remote_refresh_sec", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_refresh_sec INTEGER NOT NULL DEFAULT 300`},
		{"v2_client_entry_user_policy", "name", `ALTER TABLE v2_client_entry_user_policy ADD COLUMN name varchar(255) NOT NULL DEFAULT ''`},
		{"v2_client_entry_user_policy", "sort", `ALTER TABLE v2_client_entry_user_policy ADD COLUMN sort INTEGER NOT NULL DEFAULT 0`},
		{"v2_client_entry_user_policy", "action", `ALTER TABLE v2_client_entry_user_policy ADD COLUMN action varchar(16) NOT NULL DEFAULT 'override'`},
		{"v2_client_entry_user_policy", "conditions", `ALTER TABLE v2_client_entry_user_policy ADD COLUMN conditions text NOT NULL DEFAULT '[]'`},
		{"v2_client_entry_user_policy", "entry_host", `ALTER TABLE v2_client_entry_user_policy ADD COLUMN entry_host varchar(255) NOT NULL DEFAULT ''`},
		{"v2_server_shadowsocks", "client_entry_only", `ALTER TABLE v2_server_shadowsocks ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
		{"v2_server_vmess", "client_entry_only", `ALTER TABLE v2_server_vmess ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
		{"v2_server_vless", "client_entry_only", `ALTER TABLE v2_server_vless ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
		{"v2_server_trojan", "client_entry_only", `ALTER TABLE v2_server_trojan ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
		{"v2_server_tuic", "client_entry_only", `ALTER TABLE v2_server_tuic ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
		{"v2_server_hysteria", "client_entry_only", `ALTER TABLE v2_server_hysteria ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
		{"v2_server_anytls", "client_entry_only", `ALTER TABLE v2_server_anytls ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
		{"v2_server_v2node", "client_entry_only", `ALTER TABLE v2_server_v2node ADD COLUMN IF NOT EXISTS client_entry_only SMALLINT NOT NULL DEFAULT 0`},
	} {
		exists, err := columnExists(ctx, db, item.table, item.column)
		if err != nil {
			return fmt.Errorf("check client entry column %s.%s: %w", item.table, item.column, err)
		}
		if !exists {
			if _, err := db.ExecContext(ctx, item.stmt); err != nil {
				return fmt.Errorf("ensure client entry column %s.%s: %w", item.table, item.column, err)
			}
		}
	}

	// The updater needs stable relation rows before converting legacy policy
	// fields.  A fresh current schema has no email column and never creates the
	// retired table.
	legacyEmail, err := columnExists(ctx, db, "v2_client_entry_user_policy", "email")
	if err != nil {
		return fmt.Errorf("check legacy client entry policy email: %w", err)
	}
	if legacyEmail {
		if err := ensureLegacyClientEntryPolicyEmailTable(ctx, db); err != nil {
			return err
		}
		// Some old installations have email as NOT NULL without a default.  The
		// one-time node-host migration inserts new structured rules before it
		// drops this retired column, so make the legacy placeholder explicit.
		if _, err := db.ExecContext(ctx, `ALTER TABLE v2_client_entry_user_policy ALTER COLUMN email SET DEFAULT ''`); err != nil {
			return fmt.Errorf("ensure legacy client entry policy email default: %w", err)
		}
		if _, err := db.ExecContext(ctx, `INSERT INTO v2_client_entry_user_policy_user (policy_id, email, created_at, updated_at)
SELECT id, lower(trim(email)), created_at, updated_at
FROM v2_client_entry_user_policy
WHERE trim(email) <> ''
ON CONFLICT DO NOTHING`); err != nil {
			return fmt.Errorf("backfill legacy client entry policy users: %w", err)
		}
	}
	legacyServerType, err := columnExists(ctx, db, "v2_client_entry_user_policy", "server_type")
	if err != nil {
		return fmt.Errorf("check legacy client entry policy member: %w", err)
	}
	if legacyServerType {
		if _, err := db.ExecContext(ctx, `INSERT INTO v2_client_entry_user_policy_member (policy_id, server_type, server_id, sort, created_at, updated_at)
SELECT id, server_type, server_id, NULL, created_at, updated_at
FROM v2_client_entry_user_policy
WHERE trim(server_type) <> '' AND server_id > 0
ON CONFLICT DO NOTHING`); err != nil {
			return fmt.Errorf("backfill legacy client entry policy members: %w", err)
		}
	}

	for _, stmt := range []string{
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_group_member_group ON v2_client_entry_group_member(entry_group_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_group_ip_group ON v2_client_entry_group_ip(entry_group_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_user_policy_sort ON v2_client_entry_user_policy(sort, id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_user_policy_member_policy ON v2_client_entry_user_policy_member(policy_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_user_policy_member_server ON v2_client_entry_user_policy_member(server_type, server_id)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry index: %w", err)
		}
	}
	return nil
}

func ensureLegacyClientEntryPolicyEmailTable(ctx context.Context, db *sql.DB) error {
	if _, err := db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS v2_client_entry_user_policy_user (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
policy_id INTEGER NOT NULL,
email varchar(255) NOT NULL,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_user_policy_user UNIQUE (policy_id, email)
)`); err != nil {
		return fmt.Errorf("ensure legacy client entry user map: %w", err)
	}
	if _, err := db.ExecContext(ctx, `CREATE INDEX IF NOT EXISTS idx_v2_client_entry_user_policy_user_email ON v2_client_entry_user_policy_user(lower(email))`); err != nil {
		return fmt.Errorf("ensure legacy client entry user map index: %w", err)
	}
	return nil
}

func columnExists(ctx context.Context, db *sql.DB, tableName, columnName string) (bool, error) {
	const query = `SELECT EXISTS (
SELECT 1 FROM information_schema.columns
WHERE table_schema = CURRENT_SCHEMA() AND table_name = $1 AND column_name = $2
)`
	var exists bool
	if err := db.QueryRowContext(ctx, query, tableName, columnName).Scan(&exists); err != nil {
		return false, err
	}
	return exists, nil
}
