package postgres

import (
	"context"
	"database/sql"
	"fmt"
)

func EnsureClientEntrySchema(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("db is nil")
	}

	for _, stmt := range []string{
		`CREATE TABLE IF NOT EXISTS v2_client_entry_group (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
code varchar(64) NOT NULL,
name varchar(255) NOT NULL,
display_name varchar(255) NOT NULL,
strategy varchar(32) NOT NULL,
hide_member_nodes SMALLINT NOT NULL DEFAULT 0,
"show" SMALLINT NOT NULL DEFAULT 1,
remote_enabled SMALLINT NOT NULL DEFAULT 0,
remote_host varchar(255) NOT NULL DEFAULT '',
remote_ssh_port INTEGER NOT NULL DEFAULT 22,
remote_ssh_user varchar(255) NOT NULL DEFAULT '',
remote_ssh_password text NOT NULL DEFAULT '',
remote_group_ref varchar(255) NOT NULL DEFAULT '',
remote_exclude_names text NOT NULL DEFAULT '[]',
remote_refresh_sec INTEGER NOT NULL DEFAULT 300,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_group_code UNIQUE (code)
)`,
		`CREATE TABLE IF NOT EXISTS v2_client_entry_group_member (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
entry_group_id INTEGER NOT NULL,
server_type varchar(16) NOT NULL,
server_id INTEGER NOT NULL,
sort INTEGER DEFAULT NULL,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_group_member UNIQUE (entry_group_id, server_type, server_id)
)`,
		`CREATE TABLE IF NOT EXISTS v2_client_entry_group_ip (
id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
entry_group_id INTEGER NOT NULL,
ip varchar(128) NOT NULL,
sort INTEGER DEFAULT NULL,
created_at INTEGER NOT NULL,
updated_at INTEGER NOT NULL,
PRIMARY KEY (id),
CONSTRAINT uniq_v2_client_entry_group_ip UNIQUE (entry_group_id, ip)
)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry table: %w", err)
		}
	}

	for _, item := range []struct {
		table  string
		column string
		stmt   string
	}{
		{"v2_client_entry_group", "remote_enabled", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_enabled SMALLINT NOT NULL DEFAULT 0`},
		{"v2_client_entry_group", "remote_host", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_host varchar(255) NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_ssh_port", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_ssh_port INTEGER NOT NULL DEFAULT 22`},
		{"v2_client_entry_group", "remote_ssh_user", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_ssh_user varchar(255) NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_ssh_password", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_ssh_password text NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_group_ref", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_group_ref varchar(255) NOT NULL DEFAULT ''`},
		{"v2_client_entry_group", "remote_exclude_names", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_exclude_names text NOT NULL DEFAULT '[]'`},
		{"v2_client_entry_group", "remote_refresh_sec", `ALTER TABLE v2_client_entry_group ADD COLUMN remote_refresh_sec INTEGER NOT NULL DEFAULT 300`},
	} {
		exists, err := columnExists(ctx, db, item.table, item.column)
		if err != nil {
			return fmt.Errorf("check client entry column %s.%s: %w", item.table, item.column, err)
		}
		if exists {
			continue
		}
		if _, err := db.ExecContext(ctx, item.stmt); err != nil {
			return fmt.Errorf("ensure client entry column %s.%s: %w", item.table, item.column, err)
		}
	}

	for _, stmt := range []string{
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_group_member_group ON v2_client_entry_group_member(entry_group_id)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_client_entry_group_ip_group ON v2_client_entry_group_ip(entry_group_id)`,
	} {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("ensure client entry index: %w", err)
		}
	}

	return nil
}

func columnExists(ctx context.Context, db *sql.DB, tableName, columnName string) (bool, error) {
	const query = `SELECT EXISTS (
SELECT 1 FROM information_schema.columns
WHERE table_schema = CURRENT_SCHEMA() AND table_name = $1 AND column_name = $2
)`
	var exists bool
	if err := db.QueryRowContext(ctx, query, tableName, columnName).Scan(&exists); err != nil {
		return false, err
	}
	return exists, nil
}
