package nodeapi

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"
)

func (s *DBService) ensureSensitiveAccessSchema(ctx context.Context) error {
	if s == nil || s.db == nil {
		return errors.New("node service unavailable")
	}
	s.sensitiveSchemaOnce.Do(func() {
		queries := []string{
			`CREATE TABLE IF NOT EXISTS v2_sensitive_access_log (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				user_id INTEGER NOT NULL,
				server_id INTEGER NOT NULL,
				server_type varchar(16) NOT NULL,
				domain varchar(255) NOT NULL,
				rule varchar(255) NOT NULL DEFAULT '',
				client_ip varchar(128) NOT NULL DEFAULT '',
				count INTEGER NOT NULL DEFAULT 1,
				first_at BIGINT NOT NULL,
				last_at BIGINT NOT NULL,
				created_at BIGINT NOT NULL,
				updated_at BIGINT NOT NULL
			)`,
			`CREATE INDEX IF NOT EXISTS idx_v2_sensitive_access_log_last_at ON v2_sensitive_access_log(last_at)`,
			`CREATE INDEX IF NOT EXISTS idx_v2_sensitive_access_log_user_id ON v2_sensitive_access_log(user_id)`,
			`CREATE INDEX IF NOT EXISTS idx_v2_sensitive_access_log_domain ON v2_sensitive_access_log(domain)`,
		}
		for _, query := range queries {
			if _, err := s.db.ExecContext(ctx, query); err != nil {
				s.sensitiveSchemaErr = fmt.Errorf("ensure sensitive access schema: %w", err)
				return
			}
		}
	})
	return s.sensitiveSchemaErr
}

func (s *DBService) ReportSensitiveAccess(ctx context.Context, req SensitiveAccessReportRequest) error {
	if s == nil || s.db == nil {
		return errors.New("node service unavailable")
	}
	req.NodeType = NormalizeNodeType(req.NodeType)
	if req.NodeID <= 0 || req.NodeType == "" {
		return errors.New("invalid node target")
	}
	if len(req.Events) == 0 {
		return nil
	}
	if err := s.ensureSensitiveAccessSchema(ctx); err != nil {
		return err
	}
	if keepDays := s.currentConfig().SubscribeGuardSensitiveLogKeepDays; keepDays > 0 {
		cutoff := time.Now().Unix() - keepDays*86400
		_, _ = s.db.ExecContext(ctx, `DELETE FROM v2_sensitive_access_log WHERE last_at > 0 AND last_at < $1`, cutoff)
	}

	now := time.Now().Unix()
	for _, event := range req.Events {
		event.Domain = strings.TrimSpace(event.Domain)
		if event.UserID <= 0 || event.Domain == "" {
			continue
		}
		if event.Count <= 0 {
			event.Count = 1
		}
		if event.FirstAt <= 0 {
			event.FirstAt = now
		}
		if event.LastAt <= 0 {
			event.LastAt = event.FirstAt
		}
		if _, err := s.db.ExecContext(ctx, `INSERT INTO v2_sensitive_access_log (user_id, server_id, server_type, domain, rule, client_ip, count, first_at, last_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10)`,
			event.UserID,
			req.NodeID,
			req.NodeType,
			event.Domain,
			strings.TrimSpace(event.Rule),
			strings.TrimSpace(event.ClientIP),
			event.Count,
			event.FirstAt,
			event.LastAt,
			now,
		); err != nil {
			return fmt.Errorf("insert sensitive access log: %w", err)
		}
	}
	return nil
}

func (s *DBService) SensitiveAccessStats(ctx context.Context, limit int64) (map[string]any, error) {
	if s == nil || s.db == nil {
		return map[string]any{}, nil
	}
	if limit <= 0 || limit > 100 {
		limit = 20
	}
	if err := s.ensureSensitiveAccessSchema(ctx); err != nil {
		return nil, err
	}

	recent, err := s.querySensitiveRecent(ctx, limit)
	if err != nil {
		return nil, err
	}
	topUsers, err := s.querySensitiveTopUsers(ctx, limit)
	if err != nil {
		return nil, err
	}
	topDomains, err := s.querySensitiveTopDomains(ctx, limit)
	if err != nil {
		return nil, err
	}
	return map[string]any{
		"recent":      recent,
		"top_users":   topUsers,
		"top_domains": topDomains,
	}, nil
}

func (s *DBService) querySensitiveRecent(ctx context.Context, limit int64) ([]map[string]any, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT l.id, l.user_id, COALESCE(u.email, '') AS email, l.server_id, l.server_type, l.domain, l.rule, l.client_ip, l.count, l.first_at, l.last_at
FROM v2_sensitive_access_log l
LEFT JOIN v2_user u ON u.id = l.user_id
ORDER BY l.last_at DESC, l.id DESC
LIMIT $1`, limit)
	if err != nil {
		return nil, fmt.Errorf("query sensitive recent: %w", err)
	}
	defer rows.Close()

	result := make([]map[string]any, 0)
	for rows.Next() {
		var id, userID, serverID, count, firstAt, lastAt int64
		var email, serverType, domain, rule, clientIP string
		if err := rows.Scan(&id, &userID, &email, &serverID, &serverType, &domain, &rule, &clientIP, &count, &firstAt, &lastAt); err != nil {
			return nil, fmt.Errorf("scan sensitive recent: %w", err)
		}
		result = append(result, map[string]any{
			"id":          id,
			"user_id":     userID,
			"email":       email,
			"server_id":   serverID,
			"server_type": serverType,
			"domain":      domain,
			"rule":        rule,
			"client_ip":   clientIP,
			"count":       count,
			"first_at":    firstAt,
			"last_at":     lastAt,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate sensitive recent: %w", err)
	}
	return result, nil
}

func (s *DBService) querySensitiveTopUsers(ctx context.Context, limit int64) ([]map[string]any, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT l.user_id, COALESCE(u.email, '') AS email, SUM(l.count) AS count, COUNT(DISTINCT l.domain) AS domain_count, COALESCE(string_agg(DISTINCT l.domain, ','), '') AS domains, COUNT(DISTINCT NULLIF(l.client_ip, '')) AS ip_count, COALESCE(string_agg(DISTINCT NULLIF(l.client_ip, ''), ','), '') AS ips
FROM v2_sensitive_access_log l
LEFT JOIN v2_user u ON u.id = l.user_id
GROUP BY l.user_id, u.email
ORDER BY count DESC
LIMIT $1`, limit)
	if err != nil {
		return nil, fmt.Errorf("query sensitive top users: %w", err)
	}
	defer rows.Close()

	result := make([]map[string]any, 0)
	for rows.Next() {
		var userID, count, domainCount, ipCount int64
		var email sql.NullString
		var domains, ips string
		if err := rows.Scan(&userID, &email, &count, &domainCount, &domains, &ipCount, &ips); err != nil {
			return nil, fmt.Errorf("scan sensitive top users: %w", err)
		}
		result = append(result, map[string]any{
			"user_id":      userID,
			"email":        email.String,
			"count":        count,
			"domain_count": domainCount,
			"domains":      splitNonEmptyCSV(domains),
			"ip_count":     ipCount,
			"ips":          splitNonEmptyCSV(ips),
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate sensitive top users: %w", err)
	}
	return result, nil
}

func splitNonEmptyCSV(raw string) []string {
	parts := strings.Split(raw, ",")
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			result = append(result, part)
		}
	}
	return result
}

func (s *DBService) querySensitiveTopDomains(ctx context.Context, limit int64) ([]map[string]any, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT l.domain, SUM(l.count) AS count
FROM v2_sensitive_access_log l
GROUP BY l.domain
ORDER BY count DESC
LIMIT $1`, limit)
	if err != nil {
		return nil, fmt.Errorf("query sensitive top domains: %w", err)
	}
	defer rows.Close()

	result := make([]map[string]any, 0)
	for rows.Next() {
		var domain string
		var count int64
		if err := rows.Scan(&domain, &count); err != nil {
			return nil, fmt.Errorf("scan sensitive top domains: %w", err)
		}
		result = append(result, map[string]any{"domain": domain, "count": count})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate sensitive top domains: %w", err)
	}
	return result, nil
}
