-- Go runtime incremental PostgreSQL update script.
--
-- Fresh installs and MySQL -> PostgreSQL migrations use install.pgsql.sql,
-- which bootstraps the complete current schema in one shot.
--
-- This file is intentionally small and idempotent. It only ensures the
-- runtime support tables used by the Go stack exist, plus narrowly scoped,
-- idempotent data-security normalizations. Compatibility DDL and best-effort
-- runtime indexes are handled by the Go updater itself, so routine updates do
-- not flood stdout with false owner errors on old PostgreSQL deployments.

ALTER TABLE "v2_server_shadowsocks" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_vmess" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_vless" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_trojan" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_tuic" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_hysteria" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_anytls" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_v2node" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_result" text DEFAULT NULL;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_claim" varchar(64) DEFAULT NULL;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_claim_expires_at" BIGINT DEFAULT NULL;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_fingerprint" varchar(64) DEFAULT NULL;

-- Recharge orders must never create withdrawable invite commission. Preserve
-- already-settled history, but close legacy unpaid/approved recharge rewards.
UPDATE "v2_order"
SET "commission_balance" = 0,
    "commission_status" = 2,
    "actual_commission_balance" = 0,
    "updated_at" = EXTRACT(EPOCH FROM NOW())::INTEGER
WHERE ("type" = 9 OR "period" = 'deposit')
  AND "commission_status" IN (0, 1)
  AND "commission_balance" <> 0;

CREATE TABLE IF NOT EXISTS "failed_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "connection" text NOT NULL,
  "queue" text NOT NULL,
  "payload" text NOT NULL,
  "exception" text NOT NULL,
  "failed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_mail_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(64) NOT NULL,
  "subject" varchar(255) NOT NULL,
  "template_name" varchar(255) NOT NULL,
  "error" text,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" text NOT NULL,
  "level" varchar(11) DEFAULT NULL,
  "host" varchar(255) DEFAULT NULL,
  "uri" varchar(255) NOT NULL,
  "method" varchar(11) NOT NULL,
  "data" text,
  "ip" varchar(128) DEFAULT NULL,
  "context" text,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_runtime_kv" (
  "k" varchar(191) NOT NULL,
  "v" text NOT NULL,
  "expire_at" BIGINT NOT NULL DEFAULT '0',
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("k")
);

CREATE TABLE IF NOT EXISTS "v2_auth_session" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "session_id" varchar(64) NOT NULL,
  "auth_data" text,
  "ip" varchar(128),
  "ua" text,
  "login_at" BIGINT NOT NULL,
  "expire_at" BIGINT NOT NULL DEFAULT '0',
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_user_session" UNIQUE ("user_id", "session_id")
);

CREATE TABLE IF NOT EXISTS "v2_client_entry_group" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(255) NOT NULL,
  "display_name" varchar(255) NOT NULL,
  "strategy" varchar(32) NOT NULL,
  "hide_member_nodes" SMALLINT NOT NULL DEFAULT '0',
  "show" SMALLINT NOT NULL DEFAULT '1',
  "remote_enabled" SMALLINT NOT NULL DEFAULT '0',
  "remote_host" varchar(255) NOT NULL DEFAULT '',
  "remote_ssh_port" INTEGER NOT NULL DEFAULT '22',
  "remote_ssh_user" varchar(255) NOT NULL DEFAULT '',
  "remote_ssh_password" text NOT NULL DEFAULT '',
  "remote_group_ref" varchar(255) NOT NULL DEFAULT '',
  "remote_exclude_names" text NOT NULL DEFAULT '[]',
  "remote_refresh_sec" INTEGER NOT NULL DEFAULT '300',
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_group_code" UNIQUE ("code")
);

CREATE TABLE IF NOT EXISTS "v2_client_entry_group_member" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entry_group_id" INTEGER NOT NULL,
  "server_type" varchar(16) NOT NULL,
  "server_id" INTEGER NOT NULL,
  "sort" INTEGER DEFAULT NULL,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_group_member" UNIQUE ("entry_group_id", "server_type", "server_id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_group_member_group" ON "v2_client_entry_group_member" ("entry_group_id");

CREATE TABLE IF NOT EXISTS "v2_client_entry_group_ip" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entry_group_id" INTEGER NOT NULL,
  "ip" varchar(128) NOT NULL,
  "sort" INTEGER DEFAULT NULL,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_group_ip" UNIQUE ("entry_group_id", "ip")
);

CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_group_ip_group" ON "v2_client_entry_group_ip" ("entry_group_id");

-- User entry rules are evaluated from top to bottom.  `sort` is an internal
-- stable ordering key; administrators only reorder rows, they never enter a
-- numeric priority.
CREATE TABLE IF NOT EXISTS "v2_client_entry_user_policy" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL DEFAULT '',
  "sort" INTEGER NOT NULL DEFAULT '0',
  "action" varchar(16) NOT NULL DEFAULT 'override',
  "conditions" text NOT NULL DEFAULT '[]',
  "entry_host" varchar(255) NOT NULL DEFAULT '',
  "resolve_entry_host" SMALLINT NOT NULL DEFAULT '0',
  "extra_nodes" text NOT NULL DEFAULT '[]',
  "extra_nodes_position" varchar(16) NOT NULL DEFAULT 'after',
  "enabled" SMALLINT NOT NULL DEFAULT '1',
  "remarks" varchar(255) NOT NULL DEFAULT '',
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "name" varchar(255) NOT NULL DEFAULT '';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "sort" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "action" varchar(16) NOT NULL DEFAULT 'override';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "conditions" text NOT NULL DEFAULT '[]';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "entry_host" varchar(255) NOT NULL DEFAULT '';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "resolve_entry_host" SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "extra_nodes" text NOT NULL DEFAULT '[]';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "extra_nodes_position" varchar(16) NOT NULL DEFAULT 'after';

CREATE TABLE IF NOT EXISTS "v2_client_entry_user_policy_member" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_id" INTEGER NOT NULL,
  "server_type" varchar(16) NOT NULL DEFAULT '',
  "server_id" INTEGER NOT NULL DEFAULT '0',
  "sort" INTEGER DEFAULT NULL,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_user_policy_member" UNIQUE ("policy_id", "server_type", "server_id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_sort" ON "v2_client_entry_user_policy" ("sort", "id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_member_policy" ON "v2_client_entry_user_policy_member" ("policy_id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_member_server" ON "v2_client_entry_user_policy_member" ("server_type", "server_id");

UPDATE "v2_user" SET "auto_renewal" = 0 WHERE "auto_renewal" IS NULL;
UPDATE "v2_user" SET "remind_expire" = 1 WHERE "remind_expire" IS NULL;
UPDATE "v2_user" SET "remind_traffic" = 1 WHERE "remind_traffic" IS NULL;

CREATE TABLE IF NOT EXISTS "v2_sensitive_access_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "server_id" INTEGER NOT NULL,
  "server_type" varchar(16) NOT NULL,
  "domain" varchar(255) NOT NULL,
  "rule" varchar(255) NOT NULL DEFAULT '',
  "client_ip" varchar(128) NOT NULL DEFAULT '',
  "count" INTEGER NOT NULL DEFAULT 1,
  "first_at" BIGINT NOT NULL,
  "last_at" BIGINT NOT NULL,
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_sensitive_access_log_last_at" ON "v2_sensitive_access_log" ("last_at");
CREATE INDEX IF NOT EXISTS "idx_v2_sensitive_access_log_user_id" ON "v2_sensitive_access_log" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_v2_sensitive_access_log_domain" ON "v2_sensitive_access_log" ("domain");
