-- Go runtime incremental PostgreSQL update script.
--
-- Fresh installs and MySQL -> PostgreSQL migrations use install.pgsql.sql,
-- which bootstraps the complete current schema in one shot.
--
-- This file is intentionally small and idempotent. It only ensures the
-- runtime support tables and indexes used by the Go stack exist, so routine
-- updates do not replay the legacy PHP migration chain and flood stdout with
-- false SQL errors.

CREATE TABLE IF NOT EXISTS "failed_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "connection" text NOT NULL,
  "queue" text NOT NULL,
  "payload" text NOT NULL,
  "exception" text NOT NULL,
  "failed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_mail_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(64) NOT NULL,
  "subject" varchar(255) NOT NULL,
  "template_name" varchar(255) NOT NULL,
  "error" text,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" text NOT NULL,
  "level" varchar(11) DEFAULT NULL,
  "host" varchar(255) DEFAULT NULL,
  "uri" varchar(255) NOT NULL,
  "method" varchar(11) NOT NULL,
  "data" text,
  "ip" varchar(128) DEFAULT NULL,
  "context" text,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_runtime_kv" (
  "k" varchar(191) NOT NULL,
  "v" text NOT NULL,
  "expire_at" BIGINT NOT NULL DEFAULT '0',
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("k")
);

CREATE INDEX IF NOT EXISTS "idx_v2_runtime_kv_expire_at" ON "v2_runtime_kv" ("expire_at");

CREATE TABLE IF NOT EXISTS "v2_auth_session" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "session_id" varchar(64) NOT NULL,
  "auth_data" text,
  "ip" varchar(128),
  "ua" text,
  "login_at" BIGINT NOT NULL,
  "expire_at" BIGINT NOT NULL DEFAULT '0',
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_user_session" UNIQUE ("user_id", "session_id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_auth_session_user_id" ON "v2_auth_session" ("user_id");

ALTER TABLE IF EXISTS "v2_invite_code"
  ALTER COLUMN "code" TYPE varchar(32) USING BTRIM("code");

ALTER TABLE IF EXISTS "v2_invite_campaign"
  ALTER COLUMN "invite_code" TYPE varchar(32)
  USING CASE
    WHEN "invite_code" IS NULL THEN NULL
    ELSE BTRIM("invite_code")
  END;

ALTER TABLE IF EXISTS "v2_invite_campaign_record"
  ALTER COLUMN "invite_code" TYPE varchar(32) USING BTRIM("invite_code");
