-- Go runtime incremental PostgreSQL update script.
--
-- Fresh installs and MySQL -> PostgreSQL migrations use install.pgsql.sql,
-- which bootstraps the complete current schema in one shot.
--
-- This file is intentionally small and idempotent. It only ensures the
-- runtime support tables used by the Go stack exist, plus narrowly scoped,
-- idempotent data-security normalizations. Compatibility DDL and best-effort
-- runtime indexes are handled by the Go updater itself, so routine updates do
-- not flood stdout with false owner errors on old PostgreSQL deployments.

ALTER TABLE "v2_server_shadowsocks" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_vmess" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_vless" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_trojan" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_tuic" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_hysteria" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_anytls" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_server_v2node" ADD COLUMN IF NOT EXISTS "client_entry_only" SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_result" text DEFAULT NULL;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_claim" varchar(64) DEFAULT NULL;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_claim_expires_at" BIGINT DEFAULT NULL;
ALTER TABLE "v2_order" ADD COLUMN IF NOT EXISTS "checkout_fingerprint" varchar(64) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS "v2_order_payment_attempt" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "order_id" INTEGER NOT NULL,
  "payment_id" INTEGER NOT NULL,
  "handling_amount" INTEGER NOT NULL DEFAULT 0,
  "amount" INTEGER NOT NULL,
  "checkout_result" text DEFAULT NULL,
  "checkout_claim" varchar(64) DEFAULT NULL,
  "checkout_claim_expires_at" BIGINT DEFAULT NULL,
  "checkout_fingerprint" varchar(64) DEFAULT NULL,
  "callback_no" varchar(255) DEFAULT NULL,
  "status" SMALLINT NOT NULL DEFAULT 0,
  "paid_at" BIGINT DEFAULT NULL,
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_order_payment_attempt_method" UNIQUE ("order_id", "payment_id"),
  CONSTRAINT "fk_v2_order_payment_attempt_order"
    FOREIGN KEY ("order_id") REFERENCES "v2_order" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_v2_order_payment_attempt_order_status"
  ON "v2_order_payment_attempt" ("order_id", "status");
CREATE INDEX IF NOT EXISTS "idx_v2_order_payment_attempt_callback"
  ON "v2_order_payment_attempt" ("payment_id", "callback_no")
  WHERE "callback_no" IS NOT NULL;

-- Preserve the currently selected or winning method of orders created by an
-- older runtime. Future checkouts keep one row per selectable payment method.
INSERT INTO "v2_order_payment_attempt" (
  "order_id", "payment_id", "handling_amount", "amount",
  "checkout_result", "checkout_claim", "checkout_claim_expires_at", "checkout_fingerprint",
  "callback_no", "status", "paid_at", "created_at", "updated_at"
)
SELECT
  "id", "payment_id", COALESCE("handling_amount", 0),
  ("total_amount"::BIGINT + COALESCE("handling_amount", 0)::BIGINT)::INTEGER,
  "checkout_result", "checkout_claim", "checkout_claim_expires_at", "checkout_fingerprint",
  "callback_no", CASE WHEN "status" IN (1, 3, 4) THEN 1 ELSE 0 END,
  "paid_at", "created_at", "updated_at"
FROM "v2_order"
WHERE "payment_id" IS NOT NULL
  AND "total_amount" >= 0
  AND COALESCE("handling_amount", 0) >= 0
  AND "total_amount"::BIGINT + COALESCE("handling_amount", 0)::BIGINT BETWEEN 1 AND 2147483647
ON CONFLICT ("order_id", "payment_id") DO NOTHING;

-- Recharge orders must never create withdrawable invite commission. Preserve
-- already-settled history, but close legacy unpaid/approved recharge rewards.
UPDATE "v2_order"
SET "commission_balance" = 0,
    "commission_status" = 2,
    "actual_commission_balance" = 0,
    "updated_at" = EXTRACT(EPOCH FROM NOW())::INTEGER
WHERE ("type" = 9 OR "period" = 'deposit')
  AND "commission_status" IN (0, 1)
  AND "commission_balance" <> 0;

CREATE TABLE IF NOT EXISTS "failed_jobs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "connection" text NOT NULL,
  "queue" text NOT NULL,
  "payload" text NOT NULL,
  "exception" text NOT NULL,
  "failed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_mail_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(64) NOT NULL,
  "subject" varchar(255) NOT NULL,
  "template_name" varchar(255) NOT NULL,
  "error" text,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" text NOT NULL,
  "level" varchar(11) DEFAULT NULL,
  "host" varchar(255) DEFAULT NULL,
  "uri" varchar(255) NOT NULL,
  "method" varchar(11) NOT NULL,
  "data" text,
  "ip" varchar(128) DEFAULT NULL,
  "context" text,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "v2_runtime_kv" (
  "k" varchar(191) NOT NULL,
  "v" text NOT NULL,
  "expire_at" BIGINT NOT NULL DEFAULT '0',
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("k")
);

CREATE TABLE IF NOT EXISTS "v2_auth_session" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "session_id" varchar(64) NOT NULL,
  "auth_data" text,
  "ip" varchar(128),
  "ua" text,
  "login_at" BIGINT NOT NULL,
  "expire_at" BIGINT NOT NULL DEFAULT '0',
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_user_session" UNIQUE ("user_id", "session_id")
);

CREATE TABLE IF NOT EXISTS "v2_client_entry_group" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" varchar(64) NOT NULL,
  "name" varchar(255) NOT NULL,
  "display_name" varchar(255) NOT NULL,
  "strategy" varchar(32) NOT NULL,
  "hide_member_nodes" SMALLINT NOT NULL DEFAULT '0',
  "show" SMALLINT NOT NULL DEFAULT '1',
  "remote_enabled" SMALLINT NOT NULL DEFAULT '0',
  "remote_host" varchar(255) NOT NULL DEFAULT '',
  "remote_ssh_port" INTEGER NOT NULL DEFAULT '22',
  "remote_ssh_user" varchar(255) NOT NULL DEFAULT '',
  "remote_ssh_password" text NOT NULL DEFAULT '',
  "remote_group_ref" varchar(255) NOT NULL DEFAULT '',
  "remote_exclude_names" text NOT NULL DEFAULT '[]',
  "remote_refresh_sec" INTEGER NOT NULL DEFAULT '300',
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_group_code" UNIQUE ("code")
);

CREATE TABLE IF NOT EXISTS "v2_client_entry_group_member" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entry_group_id" INTEGER NOT NULL,
  "server_type" varchar(16) NOT NULL,
  "server_id" INTEGER NOT NULL,
  "sort" INTEGER DEFAULT NULL,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_group_member" UNIQUE ("entry_group_id", "server_type", "server_id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_group_member_group" ON "v2_client_entry_group_member" ("entry_group_id");

CREATE TABLE IF NOT EXISTS "v2_client_entry_group_ip" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entry_group_id" INTEGER NOT NULL,
  "ip" varchar(128) NOT NULL,
  "sort" INTEGER DEFAULT NULL,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_group_ip" UNIQUE ("entry_group_id", "ip")
);

CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_group_ip_group" ON "v2_client_entry_group_ip" ("entry_group_id");

-- User entry rules are evaluated from top to bottom.  `sort` is an internal
-- stable ordering key; administrators only reorder rows, they never enter a
-- numeric priority.
CREATE TABLE IF NOT EXISTS "v2_client_entry_user_policy" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL DEFAULT '',
  "sort" INTEGER NOT NULL DEFAULT '0',
  "action" varchar(16) NOT NULL DEFAULT 'override',
  "mode" varchar(16) NOT NULL DEFAULT 'standard',
  "conditions" text NOT NULL DEFAULT '[]',
  "entry_host" varchar(255) NOT NULL DEFAULT '',
  "resolve_entry_host" SMALLINT NOT NULL DEFAULT '0',
  "extra_nodes" text NOT NULL DEFAULT '[]',
  "extra_nodes_position" varchar(16) NOT NULL DEFAULT 'after',
  "snapshot_from" BIGINT DEFAULT NULL,
  "snapshot_to" BIGINT DEFAULT NULL,
  "enabled" SMALLINT NOT NULL DEFAULT '1',
  "remarks" varchar(255) NOT NULL DEFAULT '',
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "name" varchar(255) NOT NULL DEFAULT '';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "sort" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "action" varchar(16) NOT NULL DEFAULT 'override';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "mode" varchar(16) NOT NULL DEFAULT 'standard';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "conditions" text NOT NULL DEFAULT '[]';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "entry_host" varchar(255) NOT NULL DEFAULT '';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "resolve_entry_host" SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "extra_nodes" text NOT NULL DEFAULT '[]';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "extra_nodes_position" varchar(16) NOT NULL DEFAULT 'after';
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "snapshot_from" BIGINT DEFAULT NULL;
ALTER TABLE "v2_client_entry_user_policy" ADD COLUMN IF NOT EXISTS "snapshot_to" BIGINT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS "v2_client_entry_user_policy_member" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_id" INTEGER NOT NULL,
  "server_type" varchar(16) NOT NULL DEFAULT '',
  "server_id" INTEGER NOT NULL DEFAULT '0',
  "sort" INTEGER DEFAULT NULL,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "uniq_v2_client_entry_user_policy_member" UNIQUE ("policy_id", "server_type", "server_id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_sort" ON "v2_client_entry_user_policy" ("sort", "id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_member_policy" ON "v2_client_entry_user_policy_member" ("policy_id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_member_server" ON "v2_client_entry_user_policy_member" ("server_type", "server_id");

CREATE TABLE IF NOT EXISTS "v2_user_subscribe_activity" (
  "user_id" INTEGER NOT NULL,
  "last_subscribe_at" BIGINT NOT NULL,
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("user_id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_user_subscribe_activity_last_subscribe_at" ON "v2_user_subscribe_activity" ("last_subscribe_at");

CREATE TABLE IF NOT EXISTS "v2_client_entry_user_policy_split_group" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_id" INTEGER NOT NULL,
  "parent_id" BIGINT DEFAULT NULL,
  "name" varchar(255) NOT NULL DEFAULT '',
  "path" varchar(255) NOT NULL DEFAULT '',
  "entry_host" varchar(255) NOT NULL DEFAULT '',
  "sort" INTEGER NOT NULL DEFAULT 0,
  "global_sort" BIGINT DEFAULT NULL,
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

ALTER TABLE "v2_client_entry_user_policy_split_group"
  ADD COLUMN IF NOT EXISTS "global_sort" BIGINT DEFAULT NULL;

WITH needs_backfill AS MATERIALIZED (
  SELECT EXISTS (
    SELECT 1
    FROM "v2_client_entry_user_policy_split_group" split_group
    JOIN "v2_client_entry_user_policy" policy ON policy."id" = split_group."policy_id"
    WHERE policy."mode" = 'split'
      AND split_group."global_sort" IS NULL
      AND NOT EXISTS (
        SELECT 1 FROM "v2_client_entry_user_policy_split_group" child WHERE child."parent_id" = split_group."id"
      )
  ) AS needed
), visible AS MATERIALIZED (
  SELECT 'policy'::text AS kind, policy."id"::BIGINT AS id, policy."id"::BIGINT AS policy_id,
         policy."sort"::BIGINT AS policy_sort, 0::BIGINT AS local_sort, ''::text AS path
  FROM "v2_client_entry_user_policy" policy
  CROSS JOIN needs_backfill
  WHERE needs_backfill.needed AND policy."mode" <> 'split'
  UNION ALL
  SELECT 'split_group'::text, split_group."id", split_group."policy_id"::BIGINT,
         policy."sort"::BIGINT, split_group."sort"::BIGINT, split_group."path"::text
  FROM "v2_client_entry_user_policy" policy
  JOIN "v2_client_entry_user_policy_split_group" split_group ON split_group."policy_id" = policy."id"
  CROSS JOIN needs_backfill
  WHERE needs_backfill.needed AND policy."mode" = 'split'
    AND NOT EXISTS (
      SELECT 1 FROM "v2_client_entry_user_policy_split_group" child WHERE child."parent_id" = split_group."id"
    )
), ranked AS MATERIALIZED (
  SELECT kind, id, policy_id,
         ROW_NUMBER() OVER (
           ORDER BY policy_sort ASC, CASE WHEN kind = 'policy' THEN 0 ELSE 1 END ASC,
                    local_sort ASC, path ASC, id ASC
         ) * 10 AS next_sort
  FROM visible
), updated_standard AS (
  UPDATE "v2_client_entry_user_policy" policy
  SET "sort" = ranked.next_sort::INTEGER
  FROM ranked
  WHERE ranked.kind = 'policy' AND policy."id" = ranked.id
  RETURNING policy."id"
), updated_split AS (
  UPDATE "v2_client_entry_user_policy" policy
  SET "sort" = positions.next_sort::INTEGER
  FROM (
    SELECT policy_id, MIN(next_sort) AS next_sort
    FROM ranked
    WHERE kind = 'split_group'
    GROUP BY policy_id
  ) positions
  WHERE policy."id" = positions.policy_id AND policy."mode" = 'split'
  RETURNING policy."id"
)
UPDATE "v2_client_entry_user_policy_split_group" split_group
SET "global_sort" = ranked.next_sort
FROM ranked
WHERE ranked.kind = 'split_group' AND split_group."id" = ranked.id;

CREATE TABLE IF NOT EXISTS "v2_client_entry_user_policy_split_assignment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_id" INTEGER NOT NULL,
  "user_id" INTEGER NOT NULL,
  "group_id" BIGINT NOT NULL,
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

DO $client_entry_split$
BEGIN
  ALTER TABLE "v2_client_entry_user_policy_split_group"
    ADD CONSTRAINT "uniq_v2_client_entry_user_policy_split_group_path" UNIQUE ("policy_id", "path");
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_split$;

DO $client_entry_split$
BEGIN
  ALTER TABLE "v2_client_entry_user_policy_split_group"
    ADD CONSTRAINT "fk_v2_client_entry_user_policy_split_group_policy"
    FOREIGN KEY ("policy_id") REFERENCES "v2_client_entry_user_policy" ("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_split$;

DO $client_entry_split$
BEGIN
  ALTER TABLE "v2_client_entry_user_policy_split_group"
    ADD CONSTRAINT "fk_v2_client_entry_user_policy_split_group_parent"
    FOREIGN KEY ("parent_id") REFERENCES "v2_client_entry_user_policy_split_group" ("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_split$;

DO $client_entry_split$
BEGIN
  ALTER TABLE "v2_client_entry_user_policy_split_assignment"
    ADD CONSTRAINT "uniq_v2_client_entry_user_policy_split_assignment_policy_user" UNIQUE ("policy_id", "user_id");
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_split$;

DO $client_entry_split$
BEGIN
  ALTER TABLE "v2_client_entry_user_policy_split_assignment"
    ADD CONSTRAINT "fk_v2_client_entry_user_policy_split_assignment_policy"
    FOREIGN KEY ("policy_id") REFERENCES "v2_client_entry_user_policy" ("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_split$;

DO $client_entry_split$
BEGIN
  ALTER TABLE "v2_client_entry_user_policy_split_assignment"
    ADD CONSTRAINT "fk_v2_client_entry_user_policy_split_assignment_group"
    FOREIGN KEY ("group_id") REFERENCES "v2_client_entry_user_policy_split_group" ("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL;
END
$client_entry_split$;

CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_split_group_policy" ON "v2_client_entry_user_policy_split_group" ("policy_id", "sort", "id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_split_group_global_sort" ON "v2_client_entry_user_policy_split_group" ("global_sort", "id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_split_group_parent" ON "v2_client_entry_user_policy_split_group" ("parent_id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_split_assignment_group" ON "v2_client_entry_user_policy_split_assignment" ("group_id");
CREATE INDEX IF NOT EXISTS "idx_v2_client_entry_user_policy_split_assignment_user" ON "v2_client_entry_user_policy_split_assignment" ("user_id", "policy_id");

UPDATE "v2_user" SET "auto_renewal" = 0 WHERE "auto_renewal" IS NULL;
UPDATE "v2_user" SET "remind_expire" = 1 WHERE "remind_expire" IS NULL;
UPDATE "v2_user" SET "remind_traffic" = 1 WHERE "remind_traffic" IS NULL;

CREATE TABLE IF NOT EXISTS "v2_sensitive_access_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" INTEGER NOT NULL,
  "server_id" INTEGER NOT NULL,
  "server_type" varchar(16) NOT NULL,
  "domain" varchar(255) NOT NULL,
  "rule" varchar(255) NOT NULL DEFAULT '',
  "client_ip" varchar(128) NOT NULL DEFAULT '',
  "count" INTEGER NOT NULL DEFAULT 1,
  "first_at" BIGINT NOT NULL,
  "last_at" BIGINT NOT NULL,
  "created_at" BIGINT NOT NULL,
  "updated_at" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_v2_sensitive_access_log_last_at" ON "v2_sensitive_access_log" ("last_at");
CREATE INDEX IF NOT EXISTS "idx_v2_sensitive_access_log_user_id" ON "v2_sensitive_access_log" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_v2_sensitive_access_log_domain" ON "v2_sensitive_access_log" ("domain");
