// Package appleid implements the independent Apple ID product/stock/order flow.
// It deliberately does not touch v2_order or subscription state: successful
// payments only consume one inventory item and expose its credentials.
package appleid

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"math"
	"strings"
	"sync"
	"time"

	"forest/go-api/internal/config"
	"forest/go-api/internal/payment"
)

var (
	ErrUnavailable        = errors.New("apple id service unavailable")
	ErrInvalidParameter   = errors.New("invalid parameter")
	ErrProductNotFound    = errors.New("apple id product not found")
	ErrProductDisabled    = errors.New("apple id product unavailable")
	ErrOutOfStock         = errors.New("apple id product out of stock")
	ErrOrderNotFound      = errors.New("apple id order not found")
	ErrOrderPaid          = errors.New("apple id order already paid")
	ErrDeliveryNotReady   = errors.New("apple id delivery is not ready")
	ErrInventoryNotFound  = errors.New("apple id inventory not found")
	ErrDuplicateInventory = errors.New("apple id account already exists")
)

const (
	InventoryAvailable = int64(0)
	InventoryReserved  = int64(1)
	InventorySold      = int64(2)
	InventoryDisabled  = int64(3)

	OrderPending  = int64(0)
	OrderPaid     = int64(1)
	OrderCanceled = int64(2)
	OrderRefunded = int64(3)
	OrderManual   = int64(4)

	reservationTTL = 15 * time.Minute
	BusinessType   = "apple_id"
)

type Product struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	Region            string `json:"region"`
	OwnedShadowrocket bool   `json:"owned_shadowrocket"`
	Price             int64  `json:"price"`
	AfterSales        string `json:"after_sales"`
	Enabled           bool   `json:"enabled"`
	AvailableStock    int64  `json:"available_stock"`
}

type Order struct {
	ID                int64  `json:"id"`
	BusinessType      string `json:"business_type"`
	TradeNo           string `json:"trade_no"`
	ProductID         int64  `json:"product_id"`
	ProductName       string `json:"product_name"`
	Region            string `json:"region"`
	OwnedShadowrocket bool   `json:"owned_shadowrocket"`
	AfterSales        string `json:"after_sales"`
	Price             int64  `json:"price"`
	HandlingAmount    int64  `json:"handling_amount"`
	TotalAmount       int64  `json:"total_amount"`
	Status            int64  `json:"status"`
	PaymentID         *int64 `json:"payment_id,omitempty"`
	ReservedUntil     *int64 `json:"reserved_until,omitempty"`
	CreatedAt         int64  `json:"created_at"`
	PaidAt            *int64 `json:"paid_at,omitempty"`
	UpdatedAt         int64  `json:"updated_at"`
	Delivery          bool   `json:"delivery_available"`
	inventoryID       int64
}

type Delivery struct {
	OrderID   int64  `json:"order_id"`
	TradeNo   string `json:"trade_no"`
	Account   string `json:"account"`
	Password  string `json:"password"`
	ProductID int64  `json:"product_id"`
}

type CreateOrderRequest struct {
	ProductID      int64
	IdempotencyKey string
}

// DBService is safe to use from concurrent HTTP requests. Credentials are
// encrypted using a key derived from AppKey and never included in normal logs.
type DBService struct {
	cfg       config.Config
	runtime   *config.RuntimeState
	db        *sql.DB
	ensureMu  sync.Mutex
	ensured   bool
	ensureErr error
}

func NewDBService(cfg config.Config, db *sql.DB) *DBService { return &DBService{cfg: cfg, db: db} }
func (s *DBService) WithRuntimeConfig(runtime *config.RuntimeState) *DBService {
	s.runtime = runtime
	return s
}
func (s *DBService) currentConfig() config.Config {
	if s != nil && s.runtime != nil {
		return s.runtime.CurrentConfig()
	}
	if s == nil {
		return config.Config{}
	}
	return s.cfg
}

func (s *DBService) ensureSchema(ctx context.Context) error {
	if s == nil || s.db == nil {
		return ErrUnavailable
	}
	s.ensureMu.Lock()
	defer s.ensureMu.Unlock()
	if s.ensured {
		return s.ensureErr
	}
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS v2_apple_product (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name varchar(255) NOT NULL,
			region varchar(64) NOT NULL DEFAULT '',
			owned_shadowrocket SMALLINT NOT NULL DEFAULT 0,
			price INTEGER NOT NULL CHECK (price >= 0),
			after_sales text NOT NULL DEFAULT '',
			enabled SMALLINT NOT NULL DEFAULT 1,
			created_at BIGINT NOT NULL,
			updated_at BIGINT NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS v2_apple_inventory (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			product_id BIGINT NOT NULL REFERENCES v2_apple_product(id),
			account_ciphertext text NOT NULL,
			password_ciphertext text NOT NULL,
			account_fingerprint char(64) NOT NULL DEFAULT '',
			status SMALLINT NOT NULL DEFAULT 0 CHECK (status BETWEEN 0 AND 3),
			reserved_order_id BIGINT,
			reserved_until BIGINT,
			sold_order_id BIGINT,
			created_at BIGINT NOT NULL,
			updated_at BIGINT NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS v2_apple_order (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id INTEGER NOT NULL,
			product_id BIGINT NOT NULL REFERENCES v2_apple_product(id),
			product_name varchar(255) NOT NULL,
			region varchar(64) NOT NULL DEFAULT '',
			owned_shadowrocket SMALLINT NOT NULL DEFAULT 0,
			after_sales text NOT NULL DEFAULT '',
			price INTEGER NOT NULL CHECK (price >= 0),
			handling_amount INTEGER NOT NULL DEFAULT 0,
			trade_no varchar(64) NOT NULL UNIQUE,
			idempotency_key varchar(128) NOT NULL DEFAULT '',
			payment_id INTEGER,
			callback_no varchar(255),
			status SMALLINT NOT NULL DEFAULT 0 CHECK (status BETWEEN 0 AND 4),
			inventory_id BIGINT,
			reserved_until BIGINT,
			paid_at BIGINT,
			created_at BIGINT NOT NULL,
			updated_at BIGINT NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_apple_inventory_product_status ON v2_apple_inventory(product_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_apple_order_user_created ON v2_apple_order(user_id, created_at DESC)`,
		`CREATE TABLE IF NOT EXISTS v2_apple_order_audit (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			order_id BIGINT NOT NULL REFERENCES v2_apple_order(id) ON DELETE CASCADE,
			actor_user_id INTEGER,
			action varchar(64) NOT NULL,
			detail text NOT NULL DEFAULT '',
			created_at BIGINT NOT NULL
		)`,
		`CREATE INDEX IF NOT EXISTS idx_v2_apple_order_audit_order ON v2_apple_order_audit(order_id, id DESC)`,
	}
	stmts = append(stmts,
		`ALTER TABLE v2_apple_order ADD COLUMN IF NOT EXISTS handling_amount INTEGER NOT NULL DEFAULT 0`,
		`ALTER TABLE v2_apple_order ADD COLUMN IF NOT EXISTS idempotency_key varchar(128) NOT NULL DEFAULT ''`,
		`ALTER TABLE v2_apple_order ADD COLUMN IF NOT EXISTS inventory_id BIGINT`,
		`ALTER TABLE v2_apple_order ADD COLUMN IF NOT EXISTS reserved_until BIGINT`,
		`ALTER TABLE v2_apple_order ADD COLUMN IF NOT EXISTS owned_shadowrocket SMALLINT NOT NULL DEFAULT 0`,
		`ALTER TABLE v2_apple_order ADD COLUMN IF NOT EXISTS after_sales text NOT NULL DEFAULT ''`,
		`ALTER TABLE v2_apple_inventory ADD COLUMN IF NOT EXISTS account_fingerprint char(64) NOT NULL DEFAULT ''`,
		`CREATE UNIQUE INDEX IF NOT EXISTS uniq_v2_apple_order_user_idempotency ON v2_apple_order(user_id, idempotency_key) WHERE idempotency_key <> ''`,
		`CREATE UNIQUE INDEX IF NOT EXISTS uniq_v2_apple_inventory_account_fingerprint ON v2_apple_inventory(account_fingerprint) WHERE account_fingerprint <> ''`,
	)
	for _, stmt := range stmts {
		if _, err := s.db.ExecContext(ctx, stmt); err != nil {
			s.ensureErr = fmt.Errorf("ensure apple id schema: %w", err)
			break
		}
	}
	s.ensured = true
	return s.ensureErr
}

func (s *DBService) key() ([]byte, error) {
	secret := strings.TrimSpace(s.currentConfig().AppKey)
	if secret == "" {
		return nil, errors.New("app key is required to encrypt apple id credentials")
	}
	sum := sha256.Sum256([]byte("forest/apple-id/" + secret))
	return sum[:], nil
}

func (s *DBService) encrypt(value string) (string, error) {
	key, err := s.key()
	if err != nil {
		return "", err
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return "", err
	}
	sealed := gcm.Seal(nonce, nonce, []byte(value), nil)
	return base64.RawStdEncoding.EncodeToString(sealed), nil
}

func (s *DBService) decrypt(value string) (string, error) {
	key, err := s.key()
	if err != nil {
		return "", err
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}
	sealed, err := base64.RawStdEncoding.DecodeString(value)
	if err != nil {
		return "", errors.New("invalid encrypted credential")
	}
	if len(sealed) < gcm.NonceSize() {
		return "", errors.New("invalid encrypted credential")
	}
	plain, err := gcm.Open(nil, sealed[:gcm.NonceSize()], sealed[gcm.NonceSize():], nil)
	if err != nil {
		return "", errors.New("unable to decrypt credential")
	}
	return string(plain), nil
}

func (s *DBService) accountFingerprint(account string) (string, error) {
	key, err := s.key()
	if err != nil {
		return "", err
	}
	mac := hmac.New(sha256.New, key)
	_, _ = mac.Write([]byte("account:" + strings.ToLower(strings.TrimSpace(account))))
	return hex.EncodeToString(mac.Sum(nil)), nil
}

func (s *DBService) ReleaseExpiredReservations(ctx context.Context) error {
	if err := s.ensureSchema(ctx); err != nil {
		return err
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin apple id reservation sweep: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	if err := releaseExpiredReservationsTx(ctx, tx, time.Now().Unix()); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit apple id reservation sweep: %w", err)
	}
	return nil
}

func releaseExpiredReservationsTx(ctx context.Context, tx *sql.Tx, now int64) error {
	if _, err := tx.ExecContext(ctx, `WITH expired AS (
UPDATE v2_apple_order
SET status=$1,updated_at=$2
WHERE status=$3 AND reserved_until IS NOT NULL AND reserved_until < $2
RETURNING id
)
INSERT INTO v2_apple_order_audit(order_id,actor_user_id,action,detail,created_at)
SELECT id,NULL,'reservation_expired','',$2 FROM expired`, OrderCanceled, now, OrderPending); err != nil {
		return fmt.Errorf("expire apple id orders: %w", err)
	}
	if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_inventory
SET status=$1,reserved_order_id=NULL,reserved_until=NULL,updated_at=$2
WHERE status=$3 AND reserved_until IS NOT NULL AND reserved_until < $2`, InventoryAvailable, now, InventoryReserved); err != nil {
		return fmt.Errorf("release apple id inventory: %w", err)
	}
	return nil
}

func (s *DBService) ListProducts(ctx context.Context) ([]Product, error) {
	if err := s.ReleaseExpiredReservations(ctx); err != nil {
		return nil, err
	}
	rows, err := s.db.QueryContext(ctx, `SELECT p.id,p.name,p.region,p.owned_shadowrocket,p.price,p.after_sales,p.enabled,COALESCE((SELECT COUNT(*) FROM v2_apple_inventory i WHERE i.product_id=p.id AND i.status=0),0) FROM v2_apple_product p WHERE p.enabled=1 ORDER BY p.id ASC`)
	if err != nil {
		return nil, fmt.Errorf("list apple products: %w", err)
	}
	defer rows.Close()
	result := make([]Product, 0)
	for rows.Next() {
		var p Product
		var owned, enabled int64
		if err := rows.Scan(&p.ID, &p.Name, &p.Region, &owned, &p.Price, &p.AfterSales, &enabled, &p.AvailableStock); err != nil {
			return nil, err
		}
		p.OwnedShadowrocket = owned != 0
		p.Enabled = enabled != 0
		result = append(result, p)
	}
	return result, rows.Err()
}

const orderSelectColumns = `id,trade_no,product_id,product_name,region,owned_shadowrocket,after_sales,price,handling_amount,status,payment_id,reserved_until,created_at,paid_at,updated_at`

type rowScanner interface {
	Scan(dest ...any) error
}

func scanOrder(scanner rowScanner) (Order, error) {
	var order Order
	var owned int64
	var paymentID, reservedUntil, paidAt sql.NullInt64
	if err := scanner.Scan(
		&order.ID,
		&order.TradeNo,
		&order.ProductID,
		&order.ProductName,
		&order.Region,
		&owned,
		&order.AfterSales,
		&order.Price,
		&order.HandlingAmount,
		&order.Status,
		&paymentID,
		&reservedUntil,
		&order.CreatedAt,
		&paidAt,
		&order.UpdatedAt,
	); err != nil {
		return Order{}, err
	}
	order.BusinessType = BusinessType
	order.OwnedShadowrocket = owned != 0
	order.TotalAmount = order.Price + order.HandlingAmount
	order.Delivery = order.Status == OrderPaid
	if paymentID.Valid {
		value := paymentID.Int64
		order.PaymentID = &value
	}
	if reservedUntil.Valid {
		value := reservedUntil.Int64
		order.ReservedUntil = &value
	}
	if paidAt.Valid {
		value := paidAt.Int64
		order.PaidAt = &value
	}
	return order, nil
}

func (s *DBService) CreateOrder(ctx context.Context, userID int64, req CreateOrderRequest) (Order, error) {
	if userID <= 0 || req.ProductID <= 0 {
		return Order{}, ErrInvalidParameter
	}
	if err := s.ensureSchema(ctx); err != nil {
		return Order{}, err
	}
	key := strings.TrimSpace(req.IdempotencyKey)
	if len(key) > 128 {
		return Order{}, ErrInvalidParameter
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return Order{}, err
	}
	defer tx.Rollback()
	now := time.Now().Unix()
	if err := releaseExpiredReservationsTx(ctx, tx, now); err != nil {
		return Order{}, err
	}
	if key != "" {
		existing, err := scanOrder(tx.QueryRowContext(ctx, `SELECT `+orderSelectColumns+` FROM v2_apple_order WHERE user_id=$1 AND idempotency_key=$2`, userID, key))
		if err == nil {
			if existing.ProductID != req.ProductID {
				return Order{}, ErrInvalidParameter
			}
			// releaseExpiredReservationsTx ran in this transaction before the
			// idempotency lookup. Commit so an expired matching order stays
			// canceled instead of being restored by the deferred rollback.
			if err := tx.Commit(); err != nil {
				return Order{}, err
			}
			return existing, nil
		}
		if !errors.Is(err, sql.ErrNoRows) {
			return Order{}, err
		}
	}
	var p Product
	var owned, enabled int64
	if err := tx.QueryRowContext(ctx, `SELECT id,name,region,owned_shadowrocket,price,after_sales,enabled FROM v2_apple_product WHERE id=$1 FOR SHARE`, req.ProductID).Scan(&p.ID, &p.Name, &p.Region, &owned, &p.Price, &p.AfterSales, &enabled); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Order{}, ErrProductNotFound
		}
		return Order{}, err
	}
	if enabled == 0 {
		return Order{}, ErrProductDisabled
	}
	if p.Price < 0 {
		return Order{}, ErrInvalidParameter
	}
	trade := newTradeNo()
	reservedUntil := now + int64(reservationTTL/time.Second)
	order, err := scanOrder(tx.QueryRowContext(ctx, `INSERT INTO v2_apple_order(
user_id,product_id,product_name,region,owned_shadowrocket,after_sales,price,trade_no,idempotency_key,status,reserved_until,created_at,updated_at
) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12)
ON CONFLICT (user_id,idempotency_key) WHERE idempotency_key <> '' DO NOTHING
RETURNING `+orderSelectColumns,
		userID, p.ID, p.Name, p.Region, owned, p.AfterSales, p.Price, trade, key, OrderPending, reservedUntil, now))
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) && key != "" {
			existing, lookupErr := scanOrder(tx.QueryRowContext(ctx, `SELECT `+orderSelectColumns+` FROM v2_apple_order WHERE user_id=$1 AND idempotency_key=$2`, userID, key))
			if lookupErr == nil {
				if existing.ProductID != req.ProductID {
					return Order{}, ErrInvalidParameter
				}
				if err := tx.Commit(); err != nil {
					return Order{}, err
				}
				return existing, nil
			}
			return Order{}, lookupErr
		}
		return Order{}, fmt.Errorf("insert apple id order: %w", err)
	}
	var inventoryID int64
	if err := tx.QueryRowContext(ctx, `UPDATE v2_apple_inventory SET status=$1,reserved_order_id=$2,reserved_until=$3,updated_at=$4 WHERE id=(SELECT id FROM v2_apple_inventory WHERE product_id=$5 AND status=$6 ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1) RETURNING id`, InventoryReserved, order.ID, reservedUntil, now, p.ID, InventoryAvailable).Scan(&inventoryID); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Order{}, ErrOutOfStock
		}
		return Order{}, fmt.Errorf("reserve apple id inventory: %w", err)
	}
	order.inventoryID = inventoryID
	if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_order SET inventory_id=$2 WHERE id=$1`, order.ID, inventoryID); err != nil {
		return Order{}, err
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO v2_apple_order_audit(order_id,actor_user_id,action,detail,created_at) VALUES($1,$2,'created','',$3)`, order.ID, userID, now); err != nil {
		return Order{}, fmt.Errorf("audit apple id order creation: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return Order{}, err
	}
	return order, nil
}

func newTradeNo() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("apple-%d", time.Now().UnixNano())
	}
	return "apple-" + base64.RawURLEncoding.EncodeToString(b)
}

var _ payment.ExternalOrderManager = (*DBService)(nil)

func (s *DBService) OwnsExternalTradeNo(tradeNo string) bool {
	return strings.HasPrefix(strings.TrimSpace(tradeNo), "apple-")
}

func (s *DBService) LookupExternalOrder(ctx context.Context, userID int64, tradeNo string) (payment.ExternalOrder, error) {
	if err := s.ReleaseExpiredReservations(ctx); err != nil {
		return payment.ExternalOrder{}, err
	}
	tradeNo = strings.TrimSpace(tradeNo)
	if userID <= 0 || tradeNo == "" {
		return payment.ExternalOrder{}, ErrInvalidParameter
	}
	var result payment.ExternalOrder
	var payID sql.NullInt64
	err := s.db.QueryRowContext(ctx, `SELECT o.trade_no,o.price,o.handling_amount,o.status,o.payment_id,u.email
FROM v2_apple_order o
JOIN v2_user u ON u.id=o.user_id
WHERE o.user_id=$1 AND o.trade_no=$2
LIMIT 1`, userID, tradeNo).Scan(&result.TradeNo, &result.TotalAmount, &result.HandlingAmount, &result.Status, &payID, &result.UserEmail)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return payment.ExternalOrder{}, ErrOrderNotFound
		}
		return payment.ExternalOrder{}, err
	}
	if payID.Valid {
		result.PaymentID = payID.Int64
	}
	result.ReturnPath = "/#/apple-id/orders/" + result.TradeNo
	return result, nil
}

func (s *DBService) SetExternalPayment(ctx context.Context, userID int64, tradeNo string, paymentID, handlingAmount int64) error {
	if err := s.ensureSchema(ctx); err != nil {
		return err
	}
	if userID <= 0 || paymentID <= 0 || handlingAmount < 0 || !s.OwnsExternalTradeNo(tradeNo) {
		return ErrInvalidParameter
	}
	res, err := s.db.ExecContext(ctx, `UPDATE v2_apple_order
SET payment_id=$3,handling_amount=$4,updated_at=$5
WHERE user_id=$1 AND trade_no=$2 AND status=$6`, userID, strings.TrimSpace(tradeNo), paymentID, handlingAmount, time.Now().Unix(), OrderPending)
	if err != nil {
		return fmt.Errorf("set apple order payment: %w", err)
	}
	count, _ := res.RowsAffected()
	if count == 0 {
		return payment.ErrOrderPaidOrMissing
	}
	return nil
}

func (s *DBService) MarkExternalPaid(ctx context.Context, tradeNo, callbackNo string, allowCancelled bool, paymentID, amount *int64) error {
	if err := s.ensureSchema(ctx); err != nil {
		return err
	}
	tradeNo = strings.TrimSpace(tradeNo)
	callbackNo = strings.TrimSpace(callbackNo)
	if tradeNo == "" || callbackNo == "" {
		return ErrInvalidParameter
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var orderID, productID, status int64
	var inventoryID sql.NullInt64
	var reservedUntil sql.NullInt64
	var storedPaymentID, price, handlingAmount sql.NullInt64
	err = tx.QueryRowContext(ctx, `SELECT id,product_id,inventory_id,status,reserved_until,payment_id,price,handling_amount FROM v2_apple_order WHERE trade_no=$1 FOR UPDATE`, tradeNo).Scan(&orderID, &productID, &inventoryID, &status, &reservedUntil, &storedPaymentID, &price, &handlingAmount)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrOrderNotFound
		}
		return err
	}
	if status == OrderPaid || status == OrderManual || status == OrderRefunded {
		return nil
	}
	if paymentID == nil && amount == nil {
		// Internal zero-price fulfillment has no gateway evidence.
	} else if paymentID == nil || amount == nil {
		if !storedPaymentID.Valid || *paymentID != storedPaymentID.Int64 || *amount <= 0 || !price.Valid || !handlingAmount.Valid || price.Int64 > math.MaxInt64-handlingAmount.Int64 || *amount != price.Int64+handlingAmount.Int64 {
			return ErrInvalidParameter
		}
	}
	if status != OrderPending && status != OrderCanceled {
		return ErrOrderPaid
	}
	now := time.Now().Unix()
	fulfilledInventoryID := int64(0)
	if status == OrderPending && inventoryID.Valid {
		var inventoryStatus int64
		var reservedOrderID sql.NullInt64
		var inventoryReservedUntil sql.NullInt64
		err := tx.QueryRowContext(ctx, `SELECT status,reserved_order_id,reserved_until FROM v2_apple_inventory WHERE id=$1 FOR UPDATE`, inventoryID.Int64).Scan(&inventoryStatus, &reservedOrderID, &inventoryReservedUntil)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("lock reserved apple id inventory: %w", err)
		}
		reservationActive := !reservedUntil.Valid || reservedUntil.Int64 >= now
		if inventoryReservedUntil.Valid && inventoryReservedUntil.Int64 < now {
			reservationActive = false
		}
		if err == nil && inventoryStatus == InventoryReserved && reservedOrderID.Valid && reservedOrderID.Int64 == orderID {
			if reservationActive {
				if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_inventory SET status=$1,sold_order_id=$2,reserved_order_id=NULL,reserved_until=NULL,updated_at=$3 WHERE id=$4`, InventorySold, orderID, now, inventoryID.Int64); err != nil {
					return fmt.Errorf("sell reserved apple id inventory: %w", err)
				}
				fulfilledInventoryID = inventoryID.Int64
			} else {
				// The callback arrived after this reservation expired but before
				// the periodic sweep. Release the stale row before looking for a
				// replacement, so it cannot remain stuck as reserved.
				if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_inventory SET status=$1,reserved_order_id=NULL,reserved_until=NULL,updated_at=$2 WHERE id=$3 AND status=$4 AND reserved_order_id=$5`, InventoryAvailable, now, inventoryID.Int64, InventoryReserved, orderID); err != nil {
					return fmt.Errorf("release expired apple id inventory: %w", err)
				}
			}
		}
	}

	// A late callback may arrive after the original reservation was released.
	// Allocate another available item when possible; otherwise retain the paid
	// order for explicit refund or manual handling.
	if fulfilledInventoryID == 0 {
		err := tx.QueryRowContext(ctx, `UPDATE v2_apple_inventory
SET status=$1,sold_order_id=$2,reserved_order_id=NULL,reserved_until=NULL,updated_at=$3
WHERE id=(SELECT id FROM v2_apple_inventory WHERE product_id=$4 AND status=$5 ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1)
RETURNING id`, InventorySold, orderID, now, productID, InventoryAvailable).Scan(&fulfilledInventoryID)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("allocate apple id inventory after payment: %w", err)
		}
	}

	if fulfilledInventoryID == 0 {
		if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_order SET status=$1,inventory_id=NULL,callback_no=$2,paid_at=$3,updated_at=$3 WHERE id=$4`, OrderManual, callbackNo, now, orderID); err != nil {
			return fmt.Errorf("mark apple id order for manual handling: %w", err)
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO v2_apple_order_audit(order_id,actor_user_id,action,detail,created_at) VALUES($1,NULL,'late_payment','inventory unavailable; refund or manual fulfillment required',$2)`, orderID, now); err != nil {
			return fmt.Errorf("audit late apple id payment: %w", err)
		}
		return tx.Commit()
	}

	if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_order SET status=$1,inventory_id=$2,callback_no=$3,paid_at=$4,updated_at=$4 WHERE id=$5`, OrderPaid, fulfilledInventoryID, callbackNo, now, orderID); err != nil {
		return fmt.Errorf("complete apple id order: %w", err)
	}
	action := "paid"
	if status == OrderCanceled {
		action = "late_payment_fulfilled"
	}
	if allowCancelled {
		action = "manual_paid"
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO v2_apple_order_audit(order_id,actor_user_id,action,detail,created_at) VALUES($1,NULL,$2,$3,$4)`, orderID, action, callbackNo, now); err != nil {
		return fmt.Errorf("audit apple id payment: %w", err)
	}
	return tx.Commit()
}

func (s *DBService) ListOrders(ctx context.Context, userID int64) ([]Order, error) {
	if err := s.ReleaseExpiredReservations(ctx); err != nil {
		return nil, err
	}
	if userID <= 0 {
		return nil, ErrInvalidParameter
	}
	rows, err := s.db.QueryContext(ctx, `SELECT `+orderSelectColumns+` FROM v2_apple_order WHERE user_id=$1 ORDER BY created_at DESC`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := make([]Order, 0)
	for rows.Next() {
		o, err := scanOrder(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

func (s *DBService) OrderDetail(ctx context.Context, userID int64, tradeNo string) (Order, error) {
	if userID <= 0 || !s.OwnsExternalTradeNo(tradeNo) {
		return Order{}, ErrInvalidParameter
	}
	if err := s.ReleaseExpiredReservations(ctx); err != nil {
		return Order{}, err
	}
	o, err := scanOrder(s.db.QueryRowContext(ctx, `SELECT `+orderSelectColumns+` FROM v2_apple_order WHERE user_id=$1 AND trade_no=$2`, userID, strings.TrimSpace(tradeNo)))
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Order{}, ErrOrderNotFound
		}
		return Order{}, err
	}
	return o, nil
}

func (s *DBService) Delivery(ctx context.Context, userID int64, tradeNo string) (Delivery, error) {
	if userID <= 0 || !s.OwnsExternalTradeNo(tradeNo) {
		return Delivery{}, ErrInvalidParameter
	}
	if err := s.ensureSchema(ctx); err != nil {
		return Delivery{}, err
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return Delivery{}, err
	}
	defer tx.Rollback()
	var orderID, productID, status int64
	var inventoryID sql.NullInt64
	var trade string
	err = tx.QueryRowContext(ctx, `SELECT id,trade_no,product_id,inventory_id,status FROM v2_apple_order WHERE user_id=$1 AND trade_no=$2 FOR SHARE`, userID, strings.TrimSpace(tradeNo)).Scan(&orderID, &trade, &productID, &inventoryID, &status)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Delivery{}, ErrOrderNotFound
		}
		return Delivery{}, err
	}
	if status != OrderPaid || !inventoryID.Valid {
		return Delivery{}, ErrDeliveryNotReady
	}
	var aCipher, pCipher string
	if err := tx.QueryRowContext(ctx, `SELECT account_ciphertext,password_ciphertext FROM v2_apple_inventory WHERE id=$1 AND status=2 AND sold_order_id=$2`, inventoryID.Int64, orderID).Scan(&aCipher, &pCipher); err != nil {
		return Delivery{}, ErrDeliveryNotReady
	}
	account, err := s.decrypt(aCipher)
	if err != nil {
		return Delivery{}, err
	}
	password, err := s.decrypt(pCipher)
	if err != nil {
		return Delivery{}, err
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO v2_apple_order_audit(order_id,actor_user_id,action,detail,created_at) VALUES($1,$2,'delivery_view','',$3)`, orderID, userID, time.Now().Unix()); err != nil {
		return Delivery{}, fmt.Errorf("audit apple id delivery view: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return Delivery{}, fmt.Errorf("commit apple id delivery view: %w", err)
	}
	return Delivery{OrderID: orderID, TradeNo: trade, Account: account, Password: password, ProductID: productID}, nil
}

func (s *DBService) CancelOrder(ctx context.Context, userID int64, tradeNo string) error {
	if userID <= 0 || !s.OwnsExternalTradeNo(tradeNo) {
		return ErrInvalidParameter
	}
	if err := s.ensureSchema(ctx); err != nil {
		return err
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var oid, invID, status int64
	if err := tx.QueryRowContext(ctx, `SELECT id,inventory_id,status FROM v2_apple_order WHERE user_id=$1 AND trade_no=$2 FOR UPDATE`, userID, strings.TrimSpace(tradeNo)).Scan(&oid, &invID, &status); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrOrderNotFound
		}
		return err
	}
	if status != OrderPending {
		return ErrOrderPaid
	}
	now := time.Now().Unix()
	if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_order SET status=2,updated_at=$2 WHERE id=$1`, oid, now); err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, `UPDATE v2_apple_inventory SET status=$1,reserved_order_id=NULL,reserved_until=NULL,updated_at=$2 WHERE id=$3 AND status=$4 AND reserved_order_id=$5`, InventoryAvailable, now, invID, InventoryReserved, oid); err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO v2_apple_order_audit(order_id,actor_user_id,action,detail,created_at) VALUES($1,$2,'cancel','',$3)`, oid, userID, now); err != nil {
		return fmt.Errorf("audit apple id order cancellation: %w", err)
	}
	return tx.Commit()
}

// AddInventory stores only encrypted credentials. It is intended for the
// authenticated admin API and accepts one account/password pair per call.
func (s *DBService) AddInventory(ctx context.Context, productID int64, account, password string) (int64, error) {
	if err := s.ensureSchema(ctx); err != nil {
		return 0, err
	}
	account = strings.TrimSpace(account)
	if productID <= 0 || account == "" || password == "" {
		return 0, ErrInvalidParameter
	}
	a, err := s.encrypt(account)
	if err != nil {
		return 0, err
	}
	p, err := s.encrypt(password)
	if err != nil {
		return 0, err
	}
	fingerprint, err := s.accountFingerprint(account)
	if err != nil {
		return 0, err
	}
	var id int64
	err = s.db.QueryRowContext(ctx, `INSERT INTO v2_apple_inventory(product_id,account_ciphertext,password_ciphertext,account_fingerprint,status,created_at,updated_at)
SELECT $1,$2,$3,$4,$5,$6,$6
WHERE EXISTS(SELECT 1 FROM v2_apple_product WHERE id=$1)
ON CONFLICT (account_fingerprint) WHERE account_fingerprint <> '' DO NOTHING
RETURNING id`, productID, a, p, fingerprint, InventoryAvailable, time.Now().Unix()).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		var productExists bool
		if lookupErr := s.db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM v2_apple_product WHERE id=$1)`, productID).Scan(&productExists); lookupErr != nil {
			return 0, lookupErr
		}
		if !productExists {
			return 0, ErrProductNotFound
		}
		return 0, ErrDuplicateInventory
	}
	if err != nil {
		return 0, fmt.Errorf("insert apple id inventory: %w", err)
	}
	return id, nil
}
